import type { GalleryGrantDraft, GalleryRecommendationDraft } from '../../src/lib/gallery/types'
import { uuid } from '../../src/lib/gallery/schema'
export const exact=(value:unknown,keys:string[]):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join()===keys.sort().join()
const text=(value:unknown,max:number):value is string=>typeof value==='string'&&value.trim().length>0&&value.length<=max&&![...value].some(c=>(c.charCodeAt(0)<32&&c!=='\n')||c==='<'||c==='>')
export function grantDraft(value:unknown,now:Date):GalleryGrantDraft{
 if(!exact(value,['clientId','label','scopes','selection','submissionIds','expiresAt'])||!text(value.clientId,200)||!/^[A-Za-z0-9._-]+$/.test(value.clientId)||!text(value.label,80)||!Array.isArray(value.scopes)||!value.scopes.length||value.scopes.length>4||new Set(value.scopes).size!==value.scopes.length||value.scopes.some(s=>!['queue:read','submission:read','artwork:read','recommendation:write'].includes(String(s)))||!['selected','all-pending'].includes(String(value.selection))||!Array.isArray(value.submissionIds)||value.submissionIds.length>50||new Set(value.submissionIds).size!==value.submissionIds.length||value.submissionIds.some(id=>!uuid(id))||(value.selection==='selected'?value.submissionIds.length===0:value.submissionIds.length!==0)||typeof value.expiresAt!=='string'||!Number.isFinite(Date.parse(value.expiresAt))||Date.parse(value.expiresAt)<=now.getTime()||Date.parse(value.expiresAt)>now.getTime()+30*86400000||new Date(value.expiresAt).toISOString()!==value.expiresAt)throw Error('invalid_metadata')
 return value as unknown as GalleryGrantDraft
}
export function recommendationDraft(value:unknown):GalleryRecommendationDraft{
 if(!value||typeof value!=='object'||Array.isArray(value))throw Error('invalid_metadata');const v=value as Record<string,unknown>
 if(!exact(v,['schemaVersion','expectedVersion','digest','idempotencyKey','assessment','findings',...('suggestedCatalogId'in v?['suggestedCatalogId']:[]),...('supersedesId'in v?['supersedesId']:[])]))throw Error('invalid_metadata')
 if(v.schemaVersion!==1||!Number.isSafeInteger(v.expectedVersion)||Number(v.expectedVersion)<1||typeof v.digest!=='string'||!/^[a-f0-9]{64}$/.test(v.digest)||!uuid(v.idempotencyKey)||!['ready-for-human-review','needs-attention','unable-to-assess'].includes(String(v.assessment))||!Array.isArray(v.findings)||v.findings.length>10||('suggestedCatalogId'in v&&(!text(v.suggestedCatalogId,200)||!/^[a-z0-9][a-z0-9-]*$/.test(v.suggestedCatalogId)))||('supersedesId'in v&&!uuid(v.supersedesId)))throw Error('invalid_metadata')
 let explanationBytes=0
 for(const f of v.findings){if(!f||typeof f!=='object'||!exact(f,['category','severity','explanation',...('evidence'in f?['evidence']:[])])||!['catalog-match','duplicate','artwork','writing-area','geometry','reference','sharing-concern'].includes(String(f.category))||!['info','warning'].includes(String(f.severity))||!text(f.explanation,1000))throw Error('invalid_metadata');explanationBytes+=new TextEncoder().encode(f.explanation).length
  if('evidence'in f){if(!Array.isArray(f.evidence)||f.evidence.length>4)throw Error('invalid_metadata');for(const e of f.evidence){if(!e||typeof e!=='object')throw Error('invalid_metadata');if(e.type==='artwork'){if(!exact(e,['type',...('region'in e?['region']:[])]))throw Error('invalid_metadata');if('region'in e){const r=e.region;if(!exact(r,['x','y','width','height'])||Object.values(r).some(n=>typeof n!=='number'||!Number.isFinite(n))||Number(r.x)<0||Number(r.y)<0||Number(r.width)<=0||Number(r.height)<=0||Number(r.x)+Number(r.width)>1||Number(r.y)+Number(r.height)>1)throw Error('invalid_metadata')}}else if(e.type==='metadata'){if(!exact(e,['type','field'])||!['catalogId','edition','package','variant','description','surface','writeInArea'].includes(String(e.field)))throw Error('invalid_metadata')}else if(e.type==='reference'){if(!exact(e,['type','url'])||!text(e.url,1500))throw Error('invalid_metadata')}else if(e.type==='duplicate'){if(!exact(e,['type','publicationId'])||!uuid(e.publicationId))throw Error('invalid_metadata')}else throw Error('invalid_metadata')}}
 }
 if(explanationBytes>4096)throw Error('limit_exceeded');return v as unknown as GalleryRecommendationDraft
}
