import type { Statement } from '../diagnostics'
import type { GalleryAgentGrant, GalleryRecommendation } from '../../src/lib/gallery/types'
import { canonicalJson, uuid } from '../../src/lib/gallery/schema'
import { verifyGalleryAgent } from './auth'
import { exact, grantDraft, recommendationDraft } from './agent-schema'
import { addDays, boundedBody, database, responseHeaders, sha256, type GalleryDatabase, type GalleryEnv } from './storage'
import { nextCursor, readCursor, reviewRecord, type StoredReviewRow } from './review'
interface GrantRow{id:string;client_id:string;label:string;scopes_json:string;selection:'selected'|'all-pending';created_at:string;expires_at:string;revoked_at:string|null;row_version:number}
interface RecRow{id:string;grant_id:string;submission_id:string;row_version:number;digest:string;body_json:string;body_hash:string;idempotency_key:string;actor_label:string;created_at:string}
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{...responseHeaders,...(status===429?{'Retry-After':'60'}:{})}})
const activeGrant=(db:GalleryDatabase,id:string,now:Date)=>db.prepare('SELECT * FROM gallery_agent_grants WHERE id=? AND revoked_at IS NULL AND expires_at>?').bind(id,now.toISOString()).first<GrantRow>()
async function projectGrant(db:GalleryDatabase,g:GrantRow):Promise<GalleryAgentGrant>{const ids=(await db.prepare('SELECT submission_id FROM gallery_agent_assignments WHERE grant_id=? ORDER BY submission_id').bind(g.id).all<{submission_id:string}>()).results;return{id:g.id,clientId:g.client_id,label:g.label,scopes:JSON.parse(g.scopes_json),selection:g.selection,submissionIds:ids.map(r=>r.submission_id),createdAt:g.created_at,expiresAt:g.expires_at,revokedAt:g.revoked_at,version:g.row_version}}
async function readJson(request:Request){if(request.headers.get('Content-Type')!=='application/json')throw Error('invalid_metadata');try{return JSON.parse(new TextDecoder().decode(await boundedBody(request,32768))) as unknown}catch(error){if(error instanceof Error&&error.message==='limit_exceeded')throw error;throw Error('invalid_metadata')}}
function activity(db:GalleryDatabase,grantId:string|null,id:string|null,action:string,result:string,now:Date,row?:StoredReviewRow):Statement{
 const key=[grantId??'anonymous',id??'none',action,result,String(row?.row_version??0),now.toISOString().slice(0,13)].join(':')
 return db.prepare(`INSERT INTO gallery_agent_activity(id,grant_id,submission_id,action,result,row_version,digest,created_at,last_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?)
 ON CONFLICT(id) DO UPDATE SET count=count+1,last_at=excluded.last_at`).bind(key,grantId,id,action,result,row?.row_version??null,row?.digest??null,now.toISOString(),now.toISOString(),addDays(now,30))
}
function quota(db:GalleryDatabase,g:GrantRow,kind:'metadata'|'image'|'recommendation',now:Date,fullImage=false){const limits={metadata:60,image:10,recommendation:6};const statements=[db.prepare('INSERT INTO gallery_agent_quota VALUES(?,1,?,?) ON CONFLICT(bucket) DO UPDATE SET used=used+1').bind(`${g.id}:${kind}:minute:${now.toISOString().slice(0,16)}`,limits[kind],addDays(now,1))];if(kind==='recommendation'||fullImage)statements.push(db.prepare('INSERT INTO gallery_agent_quota VALUES(?,1,100,?) ON CONFLICT(bucket) DO UPDATE SET used=used+1').bind(`${g.id}:${kind}:day:${now.toISOString().slice(0,10)}`,addDays(now,2)));return statements}
async function scopedRow(db:GalleryDatabase,g:GrantRow,id:string,now:Date){return db.prepare(`SELECT s.* FROM gallery_submissions s JOIN gallery_agent_grants g ON g.id=? WHERE s.id=? AND g.revoked_at IS NULL AND g.expires_at>? AND s.state='pending' AND s.expires_at>? AND (g.selection='all-pending' OR EXISTS(SELECT 1 FROM gallery_agent_assignments a WHERE a.grant_id=g.id AND a.submission_id=s.id))`).bind(g.id,id,now.toISOString(),now.toISOString()).first<StoredReviewRow>()}
const projectRec=(r:RecRow,row:StoredReviewRow):GalleryRecommendation=>({id:r.id,submissionId:r.submission_id,version:r.row_version,digest:r.digest,actorLabel:r.actor_label,createdAt:r.created_at,stale:r.row_version!==row.row_version||r.digest!==row.digest||row.state!=='pending',recommendation:JSON.parse(r.body_json)})
export interface AgentDependencies{verifyAgent?:typeof verifyGalleryAgent;now?:()=>Date}
export async function agentResponse(request:Request,env:GalleryEnv,deps:AgentDependencies={}):Promise<Response>{
 const clock=deps.now??(()=>new Date());const now=clock();let db:GalleryDatabase|undefined;let grant:GrantRow|null=null;let replayContext:{id:string;key:string;hash:string}|null=null
 try{
  if(env.GALLERY_AGENT_ENABLED!=='true'||!env.GALLERY||!env.GALLERY_ART)return json({error:'agent_unavailable'},503)
  db=database(env);const client=await(deps.verifyAgent??verifyGalleryAgent)(request,env)
  if(!client){await activity(db,null,null,'authenticate','denied',now).run();return json({error:'forbidden'},403)}
  grant=await db.prepare('SELECT * FROM gallery_agent_grants WHERE client_id=? AND revoked_at IS NULL AND expires_at>?').bind(client,now.toISOString()).first<GrantRow>()
  if(!grant){await activity(db,null,null,'grant','denied',now).run();return json({error:'forbidden'},403)}
  const url=new URL(request.url),path=url.pathname.slice('/api/gallery/v1/agent'.length)
  const match=path.match(/^\/submissions\/([a-f0-9-]+)(?:\/(artwork|thumbnail|recommendations))?$/)
  const queue=path==='/submissions'&&request.method==='GET'
  if(!queue&&(!match||!uuid(match[1])||!(request.method==='GET'&&(!match[2]||['artwork','thumbnail'].includes(match[2])))&&!(request.method==='POST'&&match[2]==='recommendations'))){await activity(db,grant.id,null,'route','denied',now).run();return json({error:'not_found'},404)}
  const operation=queue?'queue':match![2]??'detail';const scope=queue?'queue:read':operation==='recommendations'?'recommendation:write':['artwork','thumbnail'].includes(operation)?'artwork:read':'submission:read'
  if(!(JSON.parse(grant.scopes_json) as string[]).includes(scope)){await activity(db,grant.id,null,operation,'scope_denied',now).run();return json({error:'forbidden'},403)}
  if(queue){const [date,id]=readCursor(url.searchParams.get('cursor'));const rows=(await db.prepare(`SELECT s.* FROM gallery_submissions s JOIN gallery_agent_grants g ON g.id=? WHERE g.revoked_at IS NULL AND g.expires_at>? AND s.state='pending' AND s.expires_at>? AND(g.selection='all-pending' OR EXISTS(SELECT 1 FROM gallery_agent_assignments a WHERE a.grant_id=g.id AND a.submission_id=s.id)) AND(s.created_at>? OR(s.created_at=? AND s.id>?)) ORDER BY s.created_at,s.id LIMIT 25`).bind(grant.id,now.toISOString(),now.toISOString(),date,date,id).all<StoredReviewRow>()).results
   await db.batch([...quota(db,grant,'metadata',now),activity(db,grant.id,null,'queue','allowed',now),...rows.slice(0,24).map(row=>activity(db!,grant!.id,row.id,'queue-record','allowed',now,row))]);const fresh=(await Promise.all(rows.slice(0,24).map(r=>scopedRow(db!,grant!,r.id,clock())))).filter((r):r is StoredReviewRow=>!!r);const records=await Promise.all(fresh.map(r=>reviewRecord(db!,r,clock())));if(!await activeGrant(db,grant.id,clock()))return json({error:'forbidden'},403);return json({submissions:records,nextCursor:rows.length>24?nextCursor(rows[23]):null})}
  let row=await scopedRow(db,grant,match![1],now);if(!row){await activity(db,grant.id,null,operation,'not_found',now).run();return json({error:'not_found'},404)}
  if(operation==='detail'){await db.batch([...quota(db,grant,'metadata',now),activity(db,grant.id,row.id,'detail','allowed',now,row)]);const result=await reviewRecord(db,row,clock());if(!await scopedRow(db,grant,row.id,clock()))return json({error:'not_found'},404);return json(result)}
  if(operation==='artwork'||operation==='thumbnail'){
   await db.batch([...quota(db,grant,'image',now,operation==='artwork'),activity(db,grant.id,row.id,operation,'allowed',now,row)]);const asset=await db.prepare('SELECT r2_key FROM gallery_assets WHERE submission_id=? AND kind=?').bind(row.id,operation).first<{r2_key:string}>();const object=asset&&await env.GALLERY_ART.get(asset.r2_key);if(!object)return json({error:'storage_unavailable'},503);const bytes=await object.arrayBuffer();if(!await scopedRow(db,grant,row.id,clock()))return json({error:'not_found'},404);return new Response(bytes,{headers:{...responseHeaders,'Content-Type':'image/png'}})
  }
  const proposal=recommendationDraft(await readJson(request)),body=canonicalJson(proposal),hash=await sha256(body)
  replayContext={id:row.id,key:proposal.idempotencyKey,hash};
  const replay=await db.prepare('SELECT * FROM gallery_agent_recommendations WHERE grant_id=? AND idempotency_key=?').bind(grant.id,proposal.idempotencyKey).first<RecRow>();if(replay){const same=replay.body_hash===hash&&replay.submission_id===row.id;await activity(db,grant.id,row.id,'recommendations',same?'replayed':'conflict',clock(),row).run();return same?json({recommendation:projectRec(replay,row)}):json({error:'idempotency_conflict'},409)}
  if(proposal.expectedVersion!==row.row_version||proposal.digest!==row.digest){await activity(db,grant.id,row.id,'recommendations','review_changed',clock(),row).run();return json({error:'review_changed'},409)}
  if(proposal.suggestedCatalogId&&!await db.prepare('SELECT id FROM gallery_tobaccos WHERE id=? AND active=1').bind(proposal.suggestedCatalogId).first())throw Error('invalid_metadata')
  const metadata=JSON.parse(row.metadata_json!) as {evidence?:{references?:{url:string}[]}}
  for(const finding of proposal.findings)for(const evidence of finding.evidence??[]){if(evidence.type==='reference'&&!(metadata.evidence?.references ?? []).some(r=>r.url===evidence.url))throw Error('invalid_metadata');if(evidence.type==='duplicate'&&!await db.prepare("SELECT id FROM gallery_submissions WHERE id=? AND state='published'").bind(evidence.publicationId).first()&&!await scopedRow(db,grant,evidence.publicationId,clock()))throw Error('invalid_metadata')}
  if(proposal.supersedesId&&!await db.prepare('SELECT id FROM gallery_agent_recommendations WHERE id=? AND grant_id=? AND submission_id=?').bind(proposal.supersedesId,grant.id,row.id).first())throw Error('invalid_metadata')
  const recId=crypto.randomUUID(),commitTime=clock();await db.batch([...quota(db,grant,'recommendation',commitTime),db.prepare('INSERT INTO gallery_agent_recommendations VALUES(?,?,?,?,?,?,?,?,?,?)').bind(recId,grant.id,row.id,row.row_version,row.digest,body,hash,proposal.idempotencyKey,grant.label,commitTime.toISOString()),db.prepare(`INSERT INTO gallery_review_events(id,submission_id,actor,action,row_version,digest,created_at,before_version,before_digest,request_id) SELECT ?,submission_id,?,'recommendation',row_version,digest,created_at,row_version,digest,? FROM gallery_agent_recommendations WHERE id=? AND changes()=1`).bind(crypto.randomUUID(),`agent:${grant.id}`,crypto.randomUUID(),recId)])
  const saved=(await db.prepare('SELECT * FROM gallery_agent_recommendations WHERE id=?').bind(recId).first<RecRow>())!;row=(await scopedRow(db,grant,row.id,clock()))??row;return json({recommendation:projectRec(saved,row)},201)
 }catch(error){const message=error instanceof Error?error.message:'';if(message.includes('agent_limit')||message==='limit_exceeded'){if(db)await activity(db,grant?.id??null,null,'quota','limited',clock()).run().catch(()=>{});return json({error:'limit_exceeded'},429)}if(message.includes('agent_review_changed')){if(db)await activity(db,grant?.id??null,null,'recommendations','review_changed',clock()).run().catch(()=>{});return json({error:'review_changed'},409);}if(message.includes('UNIQUE constraint failed')){if(db&&grant&&replayContext){const saved=await db.prepare('SELECT * FROM gallery_agent_recommendations WHERE grant_id=? AND idempotency_key=?').bind(grant.id,replayContext.key).first<RecRow>();const current=await scopedRow(db,grant,replayContext.id,clock());if(saved&&current&&saved.submission_id===replayContext.id&&saved.body_hash===replayContext.hash)return json({recommendation:projectRec(saved,current)})}return json({error:'idempotency_conflict'},409);}if(db)await activity(db,grant?.id??null,null,'request',['invalid_metadata','invalid_filter'].includes(message)?'invalid':'unavailable',clock()).run().catch(()=>{});return json({error:['invalid_metadata','invalid_filter'].includes(message)?message:'storage_unavailable'},['invalid_metadata','invalid_filter'].includes(message)?400:503)}
}

/** Additional human-only routes. Caller already verified Access and same-origin mutations. */
export async function adminAgentResponse(request:Request,db:GalleryDatabase,admin:string,now:Date):Promise<Response|null>{
 const url=new URL(request.url),path=url.pathname.slice('/api/gallery/v1/admin'.length)
 try{
  if(path==='/agent-grants'&&request.method==='GET'){const rows=(await db.prepare('SELECT * FROM gallery_agent_grants ORDER BY (revoked_at IS NULL AND expires_at>?) DESC,created_at DESC,id LIMIT 100').bind(now.toISOString()).all<GrantRow>()).results;return json({grants:await Promise.all(rows.map(g=>projectGrant(db,g)))})}
  if(path==='/agent-grants'&&request.method==='POST'){
   const draft=grantDraft(await readJson(request),now),id=crypto.randomUUID();if((await db.prepare('SELECT COUNT(*) AS n FROM gallery_agent_grants WHERE revoked_at IS NULL AND expires_at>?').bind(now.toISOString()).first<{n:number}>())!.n>=100)return json({error:'limit_exceeded'},429)
   for(const submissionId of draft.submissionIds)if(!await db.prepare("SELECT id FROM gallery_submissions WHERE id=? AND state='pending' AND expires_at>?").bind(submissionId,now.toISOString()).first())throw Error('invalid_metadata')
   await db.batch([db.prepare('INSERT INTO gallery_agent_grants(id,client_id,label,scopes_json,selection,created_at,expires_at,creator) VALUES(?,?,?,?,?,?,?,?)').bind(id,draft.clientId,draft.label,canonicalJson(draft.scopes),draft.selection,now.toISOString(),draft.expiresAt,admin),...draft.submissionIds.map(submissionId=>db.prepare('INSERT INTO gallery_agent_assignments VALUES(?,?)').bind(id,submissionId)),db.prepare('INSERT INTO gallery_agent_grant_events VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,admin,'create',1,now.toISOString())]);return json(await projectGrant(db,(await db.prepare('SELECT * FROM gallery_agent_grants WHERE id=?').bind(id).first<GrantRow>())!),201)
  }
  const revoke=path.match(/^\/agent-grants\/([a-f0-9-]+)\/revoke$/)
  if(revoke&&uuid(revoke[1])&&request.method==='POST'){const body=await readJson(request);if(!exact(body,['expectedVersion'])||!Number.isSafeInteger(body.expectedVersion))throw Error('invalid_metadata');const results=await db.batch([db.prepare('UPDATE gallery_agent_grants SET revoked_at=?,row_version=row_version+1 WHERE id=? AND row_version=? AND revoked_at IS NULL').bind(now.toISOString(),revoke[1],body.expectedVersion),db.prepare("INSERT INTO gallery_agent_grant_events SELECT ?,id,?,'revoke',row_version,? FROM gallery_agent_grants WHERE id=? AND changes()=1").bind(crypto.randomUUID(),admin,now.toISOString(),revoke[1])]);if(!(results[0] as {meta:{changes:number}}).meta.changes)return json({error:'review_changed'},409);return json(await projectGrant(db,(await db.prepare('SELECT * FROM gallery_agent_grants WHERE id=?').bind(revoke[1]).first<GrantRow>())!))}
  if(path==='/operations'&&request.method==='GET'){const counts=await db.prepare("SELECT COALESCE(SUM(state='pending'),0) AS pending,COALESCE(SUM(state='deleting'),0) AS cleanupWaiting,COALESCE(SUM(deadline<=?),0) AS overdue,MIN(CASE WHEN deadline<=? THEN deadline END) AS oldestOverdue,COALESCE(SUM(reserved_bytes),0) AS reservedBytes FROM (SELECT *,COALESCE(deletion_due,CASE WHEN state IN('reserved','uploading','pending','preparing-publication','unpublished') THEN expires_at END) AS deadline FROM gallery_submissions)").bind(now.toISOString(),now.toISOString()).first<Record<string,unknown>>();const maintenance=await db.prepare('SELECT last_cleanup_at AS lastCleanupAt,last_cleanup_failures AS lastCleanupFailures,last_success_at AS lastSuccessfulCleanupAt FROM gallery_maintenance WHERE id=1').first<Record<string,unknown>>();return json({...counts,...maintenance})}
  const match=path.match(/^\/submissions\/([a-f0-9-]+)\/(recommendations|history)$/)
  if(match&&uuid(match[1])&&request.method==='GET'){
   const row=await db.prepare('SELECT * FROM gallery_submissions WHERE id=?').bind(match[1]).first<StoredReviewRow>();if(!row)return json({error:'not_found'},404)
   if(match[2]==='recommendations'){const record=await reviewRecord(db,row,now);if(!record.metadata)return json({recommendations:[]});const rows=(await db.prepare('SELECT * FROM gallery_agent_recommendations WHERE submission_id=? ORDER BY created_at DESC,id DESC LIMIT 100').bind(row.id).all<RecRow>()).results;return json({recommendations:rows.map(r=>projectRec(r,row))})}
   const [date,id]=readCursor(url.searchParams.get('cursor'),true);const events=(await db.prepare(`SELECT * FROM (
    SELECT id,action,CASE WHEN actor LIKE 'agent:%' THEN 'agent' WHEN actor='contributor' THEN 'contributor' WHEN actor='system' THEN 'system' ELSE 'human' END AS actorType,actor,row_version AS version,digest,created_at AS createdAt,NULL AS result,before_version AS beforeVersion,before_digest AS beforeDigest,request_id AS requestId,reason FROM gallery_review_events WHERE submission_id=?
    UNION ALL SELECT id,action,'agent' AS actorType,coalesce(grant_id,'anonymous') AS actor,row_version AS version,digest,created_at AS createdAt,result,NULL AS beforeVersion,NULL AS beforeDigest,NULL AS requestId,NULL AS reason FROM gallery_agent_activity WHERE submission_id=?
   ) WHERE(createdAt>? OR(createdAt=? AND id>?)) ORDER BY createdAt,id LIMIT 25`).bind(row.id,row.id,date,date,id).all<{id:string;createdAt:string}>()).results
   return json({events:events.slice(0,24),nextCursor:events.length>24?nextCursor({created_at:events[23].createdAt,id:events[23].id}):null})
  }
  return null
 }catch(error){const message=error instanceof Error?error.message:'';return json({error:message.includes('UNIQUE constraint failed')?'grant_exists':message==='invalid_metadata'||message==='invalid_filter'?message:'storage_unavailable'},message.includes('UNIQUE constraint failed')?409:message==='invalid_metadata'||message==='invalid_filter'?400:503)}
}
