import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import JSZip from 'jszip'
import { fixture } from '../gallery/fixtures'

for (const width of [1280, 320]) test(`single-label sharing uses one confirmation at ${width}px`, async ({ page }, testInfo) => {
  const source = await fixture(825)
  source.manifest.labels[0].research!.sources.push({ id: 'public-reference', type: 'web', role: 'package-appearance', url: 'https://example.com/product', title: 'Public product page', retrievedAt: '2026-09-18T00:00:00Z' })
  const zip = await new JSZip().file('manifest.json', JSON.stringify(source.manifest)).file('artwork/fixture-blend.png', source.png).generateAsync({ type: 'nodebuffer' })
  const writes: { method: string; body: string | null }[] = []
  await page.route('**/api/gallery/v1/**', route => {
    const request = route.request()
    const path = new URL(request.url()).pathname
    if (path.endsWith('/config')) return route.fulfill({ json: { intake: true, serving: true, turnstileSiteKey: 'test', noticeVersion: '2026-09-06-v2' } })
    if (['POST', 'PUT'].includes(request.method())) {
      writes.push({ method: request.method(), body: request.method() === 'POST' ? request.postData() : null })
      return route.fulfill({ json: { id: request.method() === 'POST' ? request.postDataJSON().submissionId : path.split('/').at(-2), state: request.method() === 'POST' ? 'reserved' : 'pending' } })
    }
    return route.fulfill({ json: { labels: [], serving: true, nextCursor: null } })
  })
  await page.route('https://challenges.cloudflare.com/turnstile/v0/api.js*', route => route.fulfill({ contentType: 'application/javascript', body: 'window.turnstile={render:function(e,o){setTimeout(function(){o.callback("local-test-token")},10);return "fixture"},remove:function(){},reset:function(){}};' }))
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/labels/print')
  await page.getByLabel('Label ZIP').setInputFiles({ name: 'label.cellarpack.zip', mimeType: 'application/zip', buffer: zip })
  await page.getByRole('button', { name: 'Add 1 label', exact: true }).click()
  const sharing = page.getByRole('region', { name: 'Share your labels' })
  await expect(sharing).toBeVisible()
  await expect(sharing.getByRole('checkbox')).toHaveCount(1)
  const confirmation = sharing.getByRole('checkbox', { name: /I created or generated/ })
  const submit = sharing.getByRole('button', { name: 'Submit for review', exact: true })
  await expect(confirmation).not.toBeChecked()
  await expect(submit).toBeDisabled()
  await sharing.screenshot({ path: testInfo.outputPath('sharing-collapsed.png') })
  const details = sharing.getByText('Edit details', { exact: true })
  await details.focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await expect(sharing.getByLabel('Edition, if known')).toBeFocused()
  const reference = sharing.getByRole('checkbox', { name: 'https://example.com/product', exact: true })
  await expect(reference).not.toBeChecked()
  expect(writes).toEqual([])
  if (width === 320) await reference.check()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('.gallery-submission').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await details.focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await expect(confirmation).toBeFocused()
  await page.keyboard.press('Space')
  expect(writes).toEqual([])
  await expect(submit).toBeEnabled()
  await submit.focus()
  await page.keyboard.press('Enter')
  await expect(sharing.getByText('Submitted for review. Your label will appear in the gallery once approved.', { exact: true })).toBeVisible()
  expect(writes.map(write => write.method)).toEqual(['POST', 'PUT'])
  const draft = JSON.parse(writes[0].body!)
  expect(draft.evidence?.references?.map((reference: { url: string }) => reference.url) ?? []).toEqual(width === 320 ? ['https://example.com/product'] : [])
  expect(writes[0].body).not.toContain('PRIVATE_')
  await expect(sharing.getByRole('img')).toHaveCount(0)
  await expect(sharing.getByRole('checkbox')).toHaveCount(0)
  await expect(sharing.getByRole('button')).toHaveCount(0)
  await expect(sharing.getByRole('region', { name: 'Submission results' })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Print 1 label', exact: true })).toBeVisible()
  await sharing.screenshot({ path: testInfo.outputPath('sharing-submitted.png') })
})
