import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import JSZip from 'jszip'
import { printablePack } from './pack'

for (const width of [1280, 320]) for (const theme of ['light', 'dark'] as const) test(`gallery AI creation uses the shared selector and saves the chosen blend at ${width}px in ${theme}`, async ({ page, context }, testInfo) => {
  await page.setViewportSize({ width, height: 900 })
  await page.emulateMedia({ colorScheme: theme, reducedMotion: theme === 'light' ? 'reduce' : 'no-preference' })
  await page.route('**/api/**', route => {
    const path = new URL(route.request().url()).pathname
    if (path.endsWith('/config')) return route.fulfill({ json: { serving: true, intake: false } })
    if (path.endsWith('/labels') || path.endsWith('/browse')) return route.fulfill({ json: { labels: [], nextCursor: null, serving: true } })
    return route.fulfill({ status: 503, body: '{}' })
  })
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/gallery')
  const trigger = page.getByRole('button', { name: 'Create custom labels', exact: true }).first()
  await expect(trigger).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Import a label ZIP' })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('gallery-entry.png'), fullPage: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Create artwork in your AI chat' })
  await expect(dialog.getByRole('heading')).toBeFocused()
  await expect(dialog).toContainText('Tin to Cellar does not run the AI chat.')
  const input = dialog.getByRole('combobox', { name: 'Find a blend' })
  const save = dialog.getByRole('button', { name: 'Add to my AI creation list' })
  await expect(save).toBeDisabled()
  await input.fill('Nightcap')
  await expect(dialog.getByRole('option', { name: 'Nightcap by Peterson', exact: true })).toBeVisible()
  await input.press('ArrowDown')
  await expect(input).toBeFocused()
  const active = await input.getAttribute('aria-activedescendant')
  await expect(page.locator(`[id="${active}"]`)).toHaveAttribute('aria-selected', 'true')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await dialog.screenshot({ path: testInfo.outputPath('blend-suggestions.png') })
  await input.press('Escape')
  await expect(input).toHaveAttribute('aria-expanded', 'false')
  await expect(dialog).toBeVisible()
  await input.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()

  await trigger.click()
  await input.fill('Nightcap')
  await dialog.getByRole('option', { name: 'Nightcap by Peterson', exact: true }).hover()
  await input.press('Enter')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('status')).toContainText('Peterson')
  await expect(save).toBeEnabled()
  await expect(dialog.getByRole('textbox', { name: 'Maker optional' })).toHaveCount(0)
  await input.press('Tab')
  await expect(save).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await input.press('Enter')
  await expect(page).toHaveURL(/\/labels\/create$/)
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toContainText('Peterson')
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toContainText('To create with AI')
  await page.reload()
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Your labels', exact: true })).toHaveAccessibleDescription('1 saved label')
  await page.getByRole('button', { name: 'Create with ChatGPT', exact: true }).click()
  await expect(page).toHaveURL(/\/labels\/artwork$/)
  await expect(page.getByRole('list', { name: 'Requested artwork' })).toContainText('NightcapPeterson')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)

  await context.route('https://chatgpt.com/**', route => route.fulfill({ contentType: 'text/html', body: '<h1>ChatGPT test destination</h1>' }))
  const copy = page.getByRole('button', { name: 'Copy instructions' })
  const pagesBeforeCopy = context.pages().length
  await copy.click()
  const launch = page.getByRole('link', { name: 'Open ChatGPT (opens in a new tab)' })
  await expect(launch).toBeVisible()
  expect(context.pages()).toHaveLength(pagesBeforeCopy)
  await copy.focus()
  await page.keyboard.press('Tab')
  await expect(launch).toBeFocused()
  const opened = context.waitForEvent('page')
  await launch.click()
  const chat = await opened
  await expect(chat).toHaveURL(/https:\/\/chatgpt.com\//)
  const url = new URL(chat.url())
  expect(url.searchParams.get('prompt')).toContain('starting with "Howdy!"')
  expect(url.searchParams.get('prompt')).not.toContain('Nightcap')
  expect(await chat.evaluate(() => window.opener)).toBeNull()
  await chat.close()
  await page.bringToFront()
  const clipboard = await page.evaluate(() => navigator.clipboard.readText())
  expect(clipboard).toContain('Nightcap')
  await expect(page.getByText('More help', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.locator('.handoff').screenshot({ path: testInfo.outputPath('chatgpt-handoff.png') })

  const zip = await JSZip.loadAsync(await printablePack())
  const manifest = JSON.parse(await zip.file('manifest.json')!.async('string'))
  manifest.labels[0].maker = 'Peterson'; manifest.labels[0].blend = 'Nightcap'
  zip.file('manifest.json', JSON.stringify(manifest))
  await page.getByRole('navigation', { name: 'Workflow' }).getByRole('link', { name: 'Gallery', exact: true }).click()
  await page.getByRole('button', { name: 'Import a label ZIP' }).click()
  await expect(page).toHaveURL(/\/labels\/print$/)
  await page.getByLabel('Label ZIP', { exact: true }).setInputFiles({ name: 'nightcap.zip', mimeType: 'application/zip', buffer: await zip.generateAsync({ type: 'nodebuffer' }) })
  await expect(page.getByRole('dialog')).toContainText('1 request ready')
  await page.getByRole('button', { name: 'Add 1 label', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Quantity for Nightcap' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Your labels', exact: true })).toHaveAccessibleDescription('1 saved label')
  await page.getByRole('navigation', { name: 'Workflow' }).getByRole('link', { name: 'Gallery', exact: true }).click()
  await page.getByRole('button', { name: 'Review & print', exact: true }).click()
  await expect(page).toHaveURL(/\/labels\/print$/)
  await expect(page.getByRole('spinbutton', { name: 'Quantity for Nightcap' })).toBeVisible()
})
