import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

for (const width of [1280, 320]) test(`gallery artwork preview supports keyboard and original image at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 900 })
  await page.route('**/api/**', route => {
    const path = new URL(route.request().url()).pathname
    if (path.endsWith('/config')) return route.fulfill({ json: { serving: true, intake: false } })
    if (path.endsWith('/browse')) return route.fulfill({ json: { labels: [{ id: 'design-one', catalogId: 'peterson-nightcap', maker: 'Peterson', blend: 'Nightcap', edition: '', altText: 'A dark blue evening design.', artworkProfileId: 'circle-2.5@1', publishedAt: '2026-09-01' }], nextCursor: null, serving: true } })
    if (/\/(artwork|thumbnail)$/.test(path)) return route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="1500" height="1500"><circle cx="750" cy="750" r="750" fill="#123456"/></svg>' })
    return route.fulfill({ status: 503, body: '{}' })
  })
  await page.goto('/gallery')
  const trigger = page.getByRole('button', { name: 'View full-resolution Nightcap by Peterson artwork' })
  await trigger.focus()
  await trigger.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Nightcap', exact: true })
  const close = dialog.getByRole('button', { name: 'Close preview' })
  const link = dialog.getByRole('link', { name: 'Open original image (new tab)' })
  await expect(close).toBeFocused()
  await expect(dialog.getByRole('img')).toHaveAttribute('src', '/api/gallery/v1/labels/design-one/artwork')
  await expect(link).toHaveAttribute('href', '/api/gallery/v1/labels/design-one/artwork')
  await expect(link).toHaveAttribute('target', '_blank')
  expect(await dialog.evaluate(element => element.scrollHeight <= element.clientHeight)).toBe(true)
  const imageBounds = await dialog.getByRole('img').boundingBox()
  expect(imageBounds!.y).toBeGreaterThanOrEqual(0)
  expect(imageBounds!.y + imageBounds!.height).toBeLessThanOrEqual(900)
  await expect(dialog.getByRole('img')).toHaveCSS('object-fit', 'contain')
  await page.keyboard.press('Tab')
  await expect(link).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await dialog.screenshot({ path: testInfo.outputPath('artwork-preview.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.press('Space')
  await close.click()
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await dialog.getByRole('img').click()
  await expect(dialog).toBeVisible()
  await page.mouse.click(4, 4)
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
})
