import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

for (const width of [1280, 320]) test(`gallery AI creation uses the shared selector and saves the chosen blend at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/api/**', route => {
    const path = new URL(route.request().url()).pathname
    if (path.endsWith('/config')) return route.fulfill({ json: { serving: true, intake: false } })
    if (path.endsWith('/labels') || path.endsWith('/browse')) return route.fulfill({ json: { labels: [], nextCursor: null, serving: true } })
    return route.fulfill({ status: 503, body: '{}' })
  })
  await page.goto('/gallery')
  const trigger = page.getByRole('button', { name: 'Create in my AI chat', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Create artwork in your AI chat' })
  await expect(dialog.getByRole('heading')).toBeFocused()
  await expect(dialog).toContainText('No request is sent to Tin to Cellar.')
  const input = dialog.getByRole('combobox', { name: 'Find a blend' })
  const save = dialog.getByRole('button', { name: 'Add to my AI creation list' })
  await expect(save).toBeDisabled()
  await input.fill('Nightcap')
  await expect(dialog.getByRole('option', { name: 'Nightcap by Peterson', exact: true })).toBeVisible()
  await input.press('ArrowDown')
  await expect(input).toBeFocused()
  const active = await input.getAttribute('aria-activedescendant')
  await expect(page.locator(`[id="${active}"]`)).toHaveAttribute('aria-selected', 'true')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await dialog.screenshot({ path: testInfo.outputPath('blend-suggestions.png') })
  await input.press('Escape')
  await expect(input).toHaveAttribute('aria-expanded', 'false')
  await expect(dialog).toBeVisible()
  await input.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()

  await trigger.click()
  await input.fill('Nightcap')
  await dialog.getByRole('option', { name: 'Nightcap by Peterson', exact: true }).click()
  await expect(dialog.getByRole('status')).toContainText('Peterson')
  await expect(save).toBeEnabled()
  await expect(dialog.getByRole('textbox', { name: 'Maker optional' })).toHaveCount(0)
  await input.press('Tab')
  await expect(save).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await save.click()
  await expect(page).toHaveURL(/\/labels\/create$/)
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toContainText('Peterson')
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toContainText('To create with AI')
  await page.reload()
  await expect(page.getByRole('article', { name: 'Nightcap', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Continue to creation', exact: true }).click()
  await expect(page).toHaveURL(/\/labels\/artwork$/)
  await expect(page.getByRole('list', { name: 'Requested artwork' })).toContainText('NightcapPeterson')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
