import { expect, test } from '@playwright/test'
import { printablePack } from './pack'

for (const width of [320, 390, 680, 681, 831, 1280]) test(`saved-design actions stay readable at ${width}px`, async ({ page }, testInfo) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, body: '{}' }))
  await page.route('https://**/*', route => route.abort())
  await page.setViewportSize({ width, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/labels/print')
  await page.getByLabel('Label ZIP').setInputFiles({ name: 'mobile-layout.zip', mimeType: 'application/zip', buffer: await printablePack() })
  await page.getByRole('button', { name: 'Add 1 label', exact: true }).click()
  await expect(page.locator('.avery-sheet')).toBeVisible()
  await page.goto('/labels/create')
  const row = page.locator('.preparation-row').first()
  await row.getByRole('button', { name: 'Change design', exact: true }).click()
  await row.getByRole('button', { name: 'Create my own', exact: true }).click()
  await expect(row).toContainText('previous design saved')
  await page.reload()
  await expect(row).toContainText('previous design saved')
  const actions = row.locator('.workspace-row-actions')
  for (const theme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme: theme })
    for (const button of await actions.getByRole('button').all()) {
      const box = await button.boundingBox()
      expect(box!.height).toBeGreaterThanOrEqual(44)
      expect(box!.height).toBeLessThanOrEqual(76)
    }
    const choose = await actions.getByRole('button', { name: 'Choose design', exact: true }).boundingBox()
    expect(choose!.width).toBeGreaterThan(120)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await row.screenshot({ path: testInfo.outputPath(`previous-design-${width}-${theme}.png`) })
  }
  await actions.getByRole('button', { name: 'Choose design', exact: true }).click()
  await expect(actions.getByRole('button', { name: 'Close choices', exact: true })).toBeVisible()
  await actions.getByRole('button', { name: 'Use previous design', exact: true }).click()
  await expect(row).toContainText('Ready to print')
  const input = page.getByRole('combobox', { name: 'Add a blend', exact: true })
  await input.fill('Mobile layout fixture')
  await input.press('Enter')
  await page.getByRole('button', { name: 'Create with AI', exact: true }).click()
  const newRow = page.getByRole('article', { name: 'Mobile layout fixture', exact: true })
  const cancel = newRow.getByRole('button', { name: 'Cancel new artwork request', exact: true })
  await expect(cancel).toBeVisible()
  const cancelBox = await cancel.boundingBox()
  expect(cancelBox!.height).toBeLessThanOrEqual(76)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await newRow.screenshot({ path: testInfo.outputPath(`new-request-${width}.png`) })
  const summary = page.locator('.label-workspace > .preparation-summary')
  await expect(summary.getByRole('button', { name: 'Continue to creation', exact: true })).toBeEnabled()
  await expect(summary.getByRole('button', { name: 'Review & print', exact: true })).toBeEnabled()
  await expect(summary).toHaveCSS('position', 'fixed')
  await page.evaluate(() => window.scrollTo(0, 0))
  const summaryBox = (await summary.boundingBox())!
  expect(Math.abs(summaryBox.y + summaryBox.height - (900 - (width > 680 ? 16 : 0)))).toBeLessThan(2)
  await page.screenshot({ path: testInfo.outputPath(`selection-bar-${width}.png`) })
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  expect(Math.abs((await summary.boundingBox())!.y - summaryBox.y)).toBeLessThan(2)
  const footerLink = page.locator('.site-footer').getByRole('link').last()
  await footerLink.focus()
  await expect(footerLink).toBeFocused()
  const footerBox = (await footerLink.boundingBox())!
  expect(footerBox.y + footerBox.height).toBeLessThanOrEqual(summaryBox.y)
  await page.emulateMedia({ media: 'print' })
  await expect(summary).toBeHidden()
  await page.emulateMedia({ media: 'screen' })
  await cancel.click()
  await expect(newRow).toContainText('Needs artwork')
})
