import { useEffect, useState } from 'react'
import { errorText, request } from './client'
type Operations = { pending: number; cleanupWaiting: number; overdue: number; oldestOverdue: string | null; lastCleanupAt: string | null; lastSuccessfulCleanupAt?: string | null; lastCleanupFailures: number; reservedBytes: number }
export function AdminOperations() {
  const [data, setData] = useState<Operations | null>(null), [error, setError] = useState('')
  const load = async () => { try { setData(await request<Operations>('/admin/operations')); setError('') } catch (e) { setError(errorText(e)) } }
  useEffect(() => { const controller = new AbortController(); void request<Operations>('/admin/operations', { signal: controller.signal }).then(setData).catch(e => { if (!controller.signal.aborted) setError(errorText(e)) }); return () => controller.abort() }, [])
  return <section className="panel" aria-label="Gallery operations"><h2>Storage and cleanup</h2><p>Expired or unpublished designs remain inaccessible while deletion is waiting. Scheduled deletion is not proof that storage cleanup has completed.</p>{error && <p role="alert">{error}</p>}{data && <dl className="gallery-operations"><div><dt>Awaiting review</dt><dd>{data.pending}</dd></div><div><dt>Reserved storage</dt><dd>{(data.reservedBytes / 1024 / 1024).toFixed(1)} MiB</dd></div><div><dt>Waiting for cleanup</dt><dd>{data.cleanupWaiting}</dd></div><div><dt>Past deletion deadline</dt><dd>{data.overdue}</dd></div><div><dt>Oldest overdue deadline</dt><dd>{data.oldestOverdue ? new Date(data.oldestOverdue).toLocaleString() : 'None'}</dd></div><div><dt>Last cleanup</dt><dd>{data.lastCleanupAt ? new Date(data.lastCleanupAt).toLocaleString() : 'No recorded run'}</dd></div><div><dt>Last successful cleanup</dt><dd>{data.lastSuccessfulCleanupAt ? new Date(data.lastSuccessfulCleanupAt).toLocaleString() : 'No recorded success'}</dd></div><div><dt>Failures in last run</dt><dd>{data.lastCleanupFailures}</dd></div></dl>}<button className="button secondary" onClick={() => void load()}>Refresh operations</button></section>
}
