import { useEffect, useState } from 'react'
import type { GalleryAgentGrant, GalleryAgentScope, GalleryGrantDraft, GalleryReviewRecord } from '../../lib/gallery/types'
import { reviewName } from './review-model'
import { errorText, request } from './client'
const scopes: GalleryAgentScope[] = ['queue:read','submission:read','artwork:read','recommendation:write']
const scopeLabels: Record<GalleryAgentScope, string> = { 'queue:read': 'Read assigned queue', 'submission:read': 'Read submission metadata', 'artwork:read': 'Read artwork', 'recommendation:write': 'Write advisory recommendations' }
export function AgentGrants() {
  const [openedAt] = useState(Date.now)
  const [grants, setGrants] = useState<GalleryAgentGrant[]>([]), [pending, setPending] = useState<GalleryReviewRecord[]>([]), [cursor, setCursor] = useState<string | null>(null)
  const [label, setLabel] = useState(''), [clientId, setClientId] = useState(''), [selectedScopes, setScopes] = useState<GalleryAgentScope[]>(scopes)
  const [selection, setSelection] = useState<'selected' | 'all-pending'>('selected'), [selected, setSelected] = useState<string[]>([])
  const [expiry, setExpiry] = useState(() => new Date(Date.now() + 29 * 86400000).toISOString().slice(0,16)), [confirmed, setConfirmed] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [status, setStatus] = useState('')
  useEffect(() => { const controller = new AbortController(); void Promise.all([request<{grants:GalleryAgentGrant[]}>('/admin/agent-grants', {signal:controller.signal}), request<{submissions:GalleryReviewRecord[];nextCursor:string|null}>('/admin/submissions?state=pending', {signal:controller.signal})]).then(([g,q]) => { setGrants(g.grants ?? []); setPending(q.submissions ?? []); setCursor(q.nextCursor) }).catch(e => { if(!controller.signal.aborted) setError(errorText(e)) }); return () => controller.abort() }, [])
  const refresh = async () => { try { const result=await request<{grants:GalleryAgentGrant[]}>('/admin/agent-grants');setGrants(result.grants);setError('') } catch(e){setError(errorText(e))} }
  const more = async () => { try { const next = await request<{submissions:GalleryReviewRecord[];nextCursor:string|null}>(`/admin/submissions?state=pending&cursor=${encodeURIComponent(cursor ?? '')}`); setPending(old => [...old,...next.submissions]); setCursor(next.nextCursor) } catch(e) {setError(errorText(e))} }
  const save = async () => { setBusy(true); setError(''); try { const draft: GalleryGrantDraft = { clientId:clientId.trim(),label:label.trim(),scopes:selectedScopes,selection,submissionIds:selection==='selected'?selected:[],expiresAt:new Date(`${expiry}Z`).toISOString() }; await request<GalleryAgentGrant>('/admin/agent-grants',{method:'POST',body:JSON.stringify(draft)}); const next=await request<{grants:GalleryAgentGrant[]}>('/admin/agent-grants');setGrants(next.grants);setConfirmed(false);setClientId('');setLabel('');setSelected([]);setStatus('Agent grant registered. Only the selected permissions are active.') }catch(e){setError(errorText(e))}finally{setBusy(false)} }
  const revoke = async (grant:GalleryAgentGrant) => {setBusy(true);setError('');try{const next=await request<GalleryAgentGrant>(`/admin/agent-grants/${grant.id}/revoke`,{method:'POST',body:JSON.stringify({expectedVersion:grant.version})});setGrants(old=>old.map(g=>g.id===next.id?next:g));setStatus('Grant revoked. Future retrieval is denied; copies already obtained cannot be recalled.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <section aria-label="Agent permissions"><h2>Advisory agent access</h2><p>Register a Cloudflare service-token client ID here. Create and store its secret through your trusted account workflow. Never paste a secret into this form. Agents can inspect permitted pending labels and leave recommendations; only you make publication decisions.</p>{error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}
    <form className="panel gallery-grant-form" onSubmit={event=>{event.preventDefault();void save()}}><h3>Register a grant</h3><label>Agent name<input required maxLength={80} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Non-secret client ID<input required autoComplete="off" maxLength={200} value={clientId} onChange={e=>setClientId(e.target.value)}/></label><label>Expires at, UTC<input required type="datetime-local" value={expiry} max={new Date(openedAt+30*86400000).toISOString().slice(0,16)} onChange={e=>setExpiry(e.target.value)}/></label><fieldset><legend>Permissions</legend>{scopes.map(scope=><label className="gallery-check" key={scope}><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={()=>setScopes(old=>old.includes(scope)?old.filter(s=>s!==scope):[...old,scope])}/>{scopeLabels[scope]}</label>)}</fieldset><fieldset><legend>Which submissions may this agent inspect?</legend><label className="gallery-check"><input type="radio" name="grant-selection" checked={selection==='selected'} onChange={()=>{setSelection('selected');setConfirmed(false)}}/>Only selected pending submissions</label><label className="gallery-check"><input type="radio" name="grant-selection" checked={selection==='all-pending'} onChange={()=>{setSelection('all-pending');setConfirmed(false)}}/>All pending submissions, including future arrivals</label>{selection==='selected'&&<><p>Choose up to 50. Access ends when a submission is no longer pending.</p>{pending.map(item=><label className="gallery-check" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={!selected.includes(item.id)&&selected.length>=50} onChange={()=>setSelected(old=>old.includes(item.id)?old.filter(id=>id!==item.id):[...old,item.id])}/>{reviewName(item)}</label>)}{cursor&&<button className="button secondary" type="button" onClick={()=>void more()}>More pending labels</button>}</>}</fieldset><label className="gallery-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize these permissions. The agent can copy permitted artwork; this does not authorize uploading it to an undisclosed remote model or sharing credentials.</label><button className="button primary" disabled={busy||!confirmed||!selectedScopes.length||(selection==='selected'&&!selected.length)}>Register agent grant</button></form>
    <h3>Registered grants</h3><button type="button" className="button secondary" onClick={()=>void refresh()}>Refresh grants</button>{!grants.length&&<p>No registered agents.</p>}<div className="gallery-grants">{grants.map(grant=><article className="panel" key={grant.id}><h4>{grant.label}</h4><p>{grant.revokedAt?'Revoked':Date.parse(grant.expiresAt)<=openedAt?'Expired':'Active'} · Expires {new Date(grant.expiresAt).toLocaleString()}</p><p className="gallery-digest">Client ID: {grant.clientId}</p><p>{grant.scopes.map(scope=>scopeLabels[scope]).join(' · ')}</p><p>{grant.selection==='all-pending'?'All pending submissions':`${grant.submissionIds.length} selected submissions`}</p>{!grant.revokedAt&&<button className="button secondary" disabled={busy} onClick={()=>void revoke(grant)}>Revoke {grant.label}</button>}</article>)}</div>
  </section>
}
