import type { ImportedCellarLabel } from '../../lib/cellarpack/types'
import { GALLERY_NOTICE_VERSION, type GalleryLabelDraftV1, type GalleryReceipt } from '../../lib/gallery/types'
import { parseGalleryDraft, publicReference } from '../../lib/gallery/schema'
import { findExactTobacco } from '../../lib/tobacco-catalog'
export const SHARING_NOTICE = 'Your ZIP is read on this device. Only labels you choose to submit are uploaded for private review. Approved labels become public so others can download and print them for personal cellaring. Authorized review tools may inspect submitted artwork.'
export const ACKNOWLEDGEMENT = 'I created or generated these label designs and want Tin to Cellar to host and share my contribution for personal cellaring. I understand that the original brand artwork may belong to others.'
export type Choice = { edition: string; package: GalleryLabelDraftV1['package']; variant: GalleryLabelDraftV1['variant']; description: string; references: string[] }
export type Attempt = { label: ImportedCellarLabel; draft: GalleryLabelDraftV1; key: string; receipt?: GalleryReceipt; error?: string; retryable?: boolean }
export const hex = (bytes: ArrayBuffer) => Array.from(new Uint8Array(bytes), byte => byte.toString(16).padStart(2, '0')).join('')
export function references(item: ImportedCellarLabel) { return item.label.research.sources.filter(source => source.type === 'web' && ['package-appearance', 'variant-identification'].includes(source.role) && publicReference(source.url)) }
export function initial(item: ImportedCellarLabel): Choice { return { edition: '', package: 'unknown', variant: 'unknown', description: `${item.label.maker} ${item.label.blend} jar label`, references: [] } }
export async function buildDraft(item: ImportedCellarLabel, choice: Choice, submissionId: string): Promise<GalleryLabelDraftV1> {
  const l = item.label, match = findExactTobacco(l.maker, l.blend)
  const imageHash = hex(await crypto.subtle.digest('SHA-256', item.artwork.data))
  if (imageHash !== item.artwork.asset.sha256) throw new Error('Artwork no longer matches the validated ZIP. Import the original pack again before sharing.')
  const area = l.writeInAreas[0]
  if (item.artwork.mediaType !== 'image/png' || l.writeInAreas.length !== 1 || !area) throw new Error('Sharing supports PNG labels with one blank writing area. This label can still be printed locally.')
  return parseGalleryDraft({ version: 1, submissionId, catalogId: match?.id ?? null, proposedIdentity: match ? null : { maker: l.maker, blend: l.blend }, package: choice.package, variant: choice.variant, edition: choice.edition, description: choice.description, surface: { shape: l.surface.shape, finishedSize: { width: l.surface.finishedSize.width, height: l.surface.finishedSize.height, unit: l.surface.finishedSize.unit }, bleed: { top: l.surface.bleed.top, right: l.surface.bleed.right, bottom: l.surface.bleed.bottom, left: l.surface.bleed.left, unit: l.surface.bleed.unit }, safeInset: { top: l.surface.safeInset.top, right: l.surface.safeInset.right, bottom: l.surface.safeInset.bottom, left: l.surface.safeInset.left, unit: l.surface.safeInset.unit } }, writeInArea: { id: area.id, purpose: area.purpose, geometry: { shape: area.geometry.shape, x: area.geometry.x, y: area.geometry.y, width: area.geometry.width, height: area.geometry.height, ...(area.geometry.cornerRadius !== undefined ? { cornerRadius: area.geometry.cornerRadius } : {}), ...(area.geometry.rotationDegrees !== undefined ? { rotationDegrees: area.geometry.rotationDegrees } : {}) }, background: { integratedInArtwork: area.background.integratedInArtwork }, overlay: { mode: area.overlay.mode } }, references: references(item).filter(source => source.type === 'web' && choice.references.includes(source.url)).map(source => ({ url: source.type === 'web' ? source.url : '', role: source.role as 'package-appearance' | 'variant-identification' })), image: { sha256: imageHash, bytes: item.artwork.data.byteLength, width: item.artwork.pixelWidth, height: item.artwork.pixelHeight }, acknowledgement: { version: GALLERY_NOTICE_VERSION, accepted: true } })
}
