import { useEffect, useRef, useState } from 'react'
import type { GalleryLabelDraftV1, GalleryReviewRecord } from '../../lib/gallery/types'
import { publicReference } from '../../lib/gallery/schema'
import { TOBACCO_CATALOG, searchTobaccos } from '../../lib/tobacco-catalog'
import { API, errorText, request } from './client'
import { PrivateImage } from './PrivateImage'
import { ReviewEvidence } from './ReviewEvidence'
import { AdminOperations } from './AdminOperations'
import { AgentGrants } from './AgentGrants'
import { CuratedIntake } from './CuratedIntake'
type QueueCounts = { pending: number; reservedBytes: number; oldestPendingAt: string | null; cleanupWaiting?: number }
type Queue = { submissions: GalleryReviewRecord[]; nextCursor: string | null; counts?: QueueCounts }
export function GalleryAdmin() {
  const [tab, setTab] = useState<'review'|'operations'|'agents'>('review')
  const [counts, setCounts] = useState<QueueCounts | null>(null)
  const [items, setItems] = useState<GalleryReviewRecord[]>([]), [cursor, setCursor] = useState<string | null>(null), [state, setState] = useState('pending')
  const [search, setSearch] = useState(''), [mappingNeeded, setMappingNeeded] = useState(false), [catalogSearch, setCatalogSearch] = useState('')
  const [current, setCurrent] = useState<GalleryReviewRecord | null>(null), [draft, setDraftValue] = useState<GalleryLabelDraftV1 | null>(null), [image, setImage] = useState('')
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [reviewed, setReviewed] = useState(false), [reason, setReason] = useState('unsuitable'), [conflict, setConflict] = useState(false)
  const reviewHeading = useRef<HTMLHeadingElement|null>(null)
  const queueController = useRef<AbortController|null>(null), detailController = useRef<AbortController|null>(null)
  const setDraft = (value:GalleryLabelDraftV1|null) => {setDraftValue(value);setReviewed(false)}
  const list = async (next?: string) => {
    queueController.current?.abort();const controller=new AbortController();queueController.current=controller;setBusy(true);setError('')
    if(!next){detailController.current?.abort();setCurrent(null);setDraft(null);setImage('');setReviewed(false);setCursor(null)}
    try { const query = new URLSearchParams({ state, ...(search?{search}:{}), ...(mappingNeeded?{mappingNeeded:'true'}:{}), ...(next ? { cursor: next } : {}) }); const result = await request<Queue>(`/admin/submissions?${query}`,{signal:controller.signal}); if(!controller.signal.aborted){setItems(old => next ? [...old, ...result.submissions] : result.submissions);setCursor(result.nextCursor);setCounts(result.counts ?? null)} } catch (e) { if(!controller.signal.aborted)setError(errorText(e)) } finally { if(!controller.signal.aborted)setBusy(false) }
  }
  useEffect(() => { const controller=new AbortController();queueController.current=controller;void request<Queue>('/admin/submissions?state=pending',{signal:controller.signal}).then(result => { if(!controller.signal.aborted){setItems(result.submissions);setCursor(result.nextCursor);setCounts(result.counts ?? null)} }).catch(e => { if(!controller.signal.aborted)setError(errorText(e)) }); return () => {queueController.current?.abort();detailController.current?.abort()} }, [])
  const open = async (id: string) => {
    detailController.current?.abort();const controller=new AbortController();detailController.current=controller;setBusy(true);setError('');setReviewed(false);setImage('');setCurrent(null);setDraft(null);setConflict(false);setCatalogSearch('')
    try { const result = await request<GalleryReviewRecord>(`/admin/submissions/${id}`,{signal:controller.signal});if(!controller.signal.aborted){setCurrent(result);setDraft(result.metadata)} } catch (e) { if(!controller.signal.aborted)setError(errorText(e)) } finally { if(!controller.signal.aborted)setBusy(false) }
  }
  useEffect(() => { if (!current) return; const controller = new AbortController(); let url = ''; void fetch(`${API}/admin/submissions/${current.id}/artwork`, { cache: 'no-store', signal: controller.signal,referrerPolicy:'no-referrer' }).then(async response => { if (!response.ok) throw new Error('Private artwork is unavailable. Reload this submission before approving.'); const blob = await response.blob(); if (!controller.signal.aborted) { url = URL.createObjectURL(blob); setImage(url) } }).catch(e => { if (!controller.signal.aborted) setError(errorText(e)) }); return () => { controller.abort(); if (url) URL.revokeObjectURL(url) } }, [current])
  useEffect(()=>{reviewHeading.current?.focus()},[current?.id])
  const action = async (kind: string) => {
    if (!current || conflict) return; setBusy(true); setError(''); setReviewed(false)
    try {
      const result = await request<GalleryReviewRecord>(`/admin/submissions/${current.id}${kind === 'save' ? '' : `/${kind}`}`, { method: kind === 'save' ? 'PATCH' : 'POST', body: JSON.stringify({ expectedVersion: current.version, ...(kind === 'save' ? { metadata: draft } : kind === 'reject' ? { reason } : kind === 'approve' ? { digest: current.digest } : {}) }) })
      setCurrent(result); setDraft(result.metadata);setItems(old=>old.map(item=>item.id===result.id?result:item))
    } catch (e) { setError(errorText(e));if(errorText(e).includes('changed'))setConflict(true) } finally { setBusy(false) }
  }
  const dirty = JSON.stringify(draft) !== JSON.stringify(current?.metadata)
  const catalogOptions = catalogSearch ? searchTobaccos(catalogSearch, 30) : TOBACCO_CATALOG
  const selectedCatalog=TOBACCO_CATALOG.find(entry=>entry.id===draft?.catalogId)
  const visibleCatalog=selectedCatalog&&!catalogOptions.some(entry=>entry.id===selectedCatalog.id)?[selectedCatalog,...catalogOptions]:catalogOptions
  return <section className="gallery-page screen-only"><h1>Review community labels</h1><p>Review the full-resolution artwork, blank writing area, tobacco match, and shared metadata. Approval publishes this exact version.</p><nav className="gallery-admin-tabs" aria-label="Administration"><button className="button secondary" aria-pressed={tab==='review'} onClick={()=>setTab('review')}>Review queue</button><button className="button secondary" aria-pressed={tab==='operations'} onClick={()=>setTab('operations')}>Operations</button><button className="button secondary" aria-pressed={tab==='agents'} onClick={()=>setTab('agents')}>Agent permissions</button></nav>{tab==='operations'&&<AdminOperations/>}{tab==='agents'&&<AgentGrants/>}{tab==='review'&&<>{error && <p role="alert">{error}</p>}
    <CuratedIntake/>
    <form className="gallery-filters" onSubmit={event => { event.preventDefault(); void list() }}><label>Submission status<select value={state} onChange={event => setState(event.target.value)}>{['pending','reserved','published','unpublished','rejected','withdrawn','expired','deleting','deleted'].map(value => <option key={value}>{value}</option>)}</select></label><label>Maker or blend<input maxLength={160} value={search} onChange={event=>setSearch(event.target.value)}/></label><label className="gallery-check"><input type="checkbox" checked={mappingNeeded} onChange={event=>setMappingNeeded(event.target.checked)}/>Needs catalog mapping</label><button className="button secondary" disabled={busy}>Refresh queue</button></form>
    {counts && <p className="field-hint">{`${counts.pending} awaiting review · ${(counts.reservedBytes / 1024 / 1024).toFixed(1)} MiB reserved${counts.oldestPendingAt ? ` · Oldest pending: ${new Date(counts.oldestPendingAt).toLocaleDateString()}` : ''}`}</p>}
    <div className="gallery-admin-layout"><section aria-label="Review queue">{items.map(item => <button className="gallery-queue-item" key={item.id} aria-current={current?.id===item.id?'true':undefined} onClick={() => void open(item.id)}><PrivateImage id={item.id} alt=""/><span><strong>{item.maker ?? item.metadata?.proposedIdentity?.maker ?? TOBACCO_CATALOG.find(entry => entry.id === item.metadata?.catalogId)?.maker} {item.blend ?? item.metadata?.proposedIdentity?.blend ?? TOBACCO_CATALOG.find(entry => entry.id === item.metadata?.catalogId)?.blend ?? item.id}</strong><span>{item.state}{item.mappingNeeded?' · Needs mapping':''}</span><span>{item.metadata?.edition || 'Edition not specified'}</span>{item.createdAt&&<time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleDateString()}</time>}</span></button>)}{!items.length && !busy && <p>No submissions in this queue.</p>}{cursor && <button className="button secondary" disabled={busy} onClick={() => void list(cursor)}>More submissions</button>}</section>
    {current && !draft && <article aria-label="Selected submission"><h2 ref={reviewHeading} tabIndex={-1}>Submission record</h2><p>Status: {current.state}. Artwork and metadata are no longer available for review.</p>{current.deletionDue&&<p>Scheduled deletion: {new Date(current.deletionDue).toLocaleString()}</p>}<ReviewEvidence key={`${current.id}:${current.version}`} record={current}/></article>}
    {current && draft && <article aria-label="Selected submission"><h2 ref={reviewHeading} tabIndex={-1}>Review label</h2><button className="button quiet" disabled={busy} onClick={()=>void open(current.id)}>Reload submission</button><p>Status: {current.state} · Version {current.version}</p>{image && <a href={image} target="_blank" rel="noreferrer"><img className="gallery-review-art" src={image} alt={draft.description} onError={()=>{setImage('');setReviewed(false);setError('Artwork could not be displayed. Reload this submission before approving.')}} /><span>Open full-resolution artwork</span></a>}<p className="gallery-digest">Approval digest: {current.digest ?? 'Not ready for approval'}</p><p>{draft.image.width} × {draft.image.height} pixels · {draft.surface.finishedSize.width} {draft.surface.finishedSize.unit} circle</p>
    <p>Current identity: {current.maker ?? draft.proposedIdentity?.maker ?? 'Not recorded'} {current.blend ?? draft.proposedIdentity?.blend ?? ''}</p>{current.publishedIdentity&&<p>Published identity: {current.publishedIdentity.maker} {current.publishedIdentity.blend}</p>}<p className="field-hint">Catalog ID: {draft.catalogId ?? 'Mapping required. Add a new blend through catalog maintenance if needed.'}</p><fieldset disabled={busy || conflict || current.state !== 'pending'}><legend>Reviewed metadata</legend><label>Search catalog<input value={catalogSearch} maxLength={160} onChange={event=>setCatalogSearch(event.target.value)}/></label><label>Tobacco match<select value={draft.catalogId ?? ''} onChange={event => { const id = event.target.value; if (id) setDraft({ ...draft, catalogId: id, proposedIdentity: null }); setReviewed(false) }}><option value="">Unmapped; catalog update required before approval</option>{visibleCatalog.map(entry => <option key={entry.id} value={entry.id}>{entry.maker} · {entry.blend}</option>)}</select></label><label>Edition<input maxLength={120} value={draft.edition} onChange={event => setDraft({ ...draft, edition: event.target.value })} /></label><label>Artwork description<input maxLength={320} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></label><label>Package<select value={draft.package} onChange={event => setDraft({ ...draft, package: event.target.value as GalleryLabelDraftV1['package'] })}>{['unknown','tin','pouch','box','bulk','other'].map(value => <option key={value}>{value}</option>)}</select></label><label>Variant<select value={draft.variant} onChange={event => setDraft({ ...draft, variant: event.target.value as GalleryLabelDraftV1['variant'] })}>{['unknown','current','historical','special'].map(value => <option key={value}>{value}</option>)}</select></label>
    {draft.references.map((reference, index) => <div key={index}><label>Reference {index + 1}<input value={reference.url} maxLength={1500} onChange={event => setDraft({ ...draft, references: draft.references.map((ref, i) => i === index ? { ...ref, url: event.target.value } : ref) })} /></label><label>Reference role {index + 1}<select value={reference.role} onChange={event=>setDraft({...draft,references:draft.references.map((ref,i)=>i===index?{...ref,role:event.target.value as 'package-appearance'|'variant-identification'}:ref)})}><option value="package-appearance">Package appearance</option><option value="variant-identification">Variant identification</option></select></label>{publicReference(reference.url) && <a href={reference.url} target="_blank" rel="noreferrer">Open reference</a>}<button className="button quiet" onClick={() => setDraft({ ...draft, references: draft.references.filter((_, i) => i !== index) })}>Remove reference</button></div>)}{draft.references.length < 3 && <button className="button quiet" onClick={() => setDraft({ ...draft, references: [...draft.references, { url: '', role: 'package-appearance' }] })}>Add public reference</button>}<button className="button secondary" disabled={!dirty} onClick={() => void action('save')}>Save corrections for review</button></fieldset>
    <ReviewEvidence key={`${current.id}:${current.version}`} record={current}/>
    <label className="gallery-check"><input type="checkbox" checked={reviewed} disabled={dirty || !image || busy || conflict} onChange={event => setReviewed(event.target.checked)} />I reviewed this artwork and the saved metadata, including its blank writing area.</label>
    <div className="gallery-actions">{current.state === 'pending' && <button className="button primary" disabled={busy || conflict || dirty || !reviewed || !draft.catalogId || !current.digest} onClick={() => void action('approve')}>Approve and publish</button>}{current.state === 'unpublished' && <button className="button primary" disabled={busy || conflict || dirty || !reviewed || !current.digest} onClick={() => void action('republish')}>Republish reviewed version</button>}{current.state === 'published' && <><button className="button secondary" disabled={busy || conflict} onClick={() => void action('refresh')}>Refresh public identity and pack</button><button className="button secondary" disabled={busy || conflict} onClick={() => void action('unpublish')}>Unpublish now</button></>}{current.state === 'pending' && <><label>Rejection reason<select value={reason} onChange={event => setReason(event.target.value)}>{['unsuitable','rights-concern','duplicate','other'].map(value => <option key={value}>{value}</option>)}</select></label><button className="button secondary" disabled={busy || conflict} onClick={() => void action('reject')}>Reject submission</button></>}</div>{current.deletionDue&&<p>Scheduled deletion: {new Date(current.deletionDue).toLocaleString()}</p>}<p>Unpublishing stops subsequent downloads. Copies already downloaded cannot be recalled.</p></article>}
    </div>{busy && <p role="status">Updating review…</p>}</>}
  </section>
}
