import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { randomBytes, createHash } from 'node:crypto'
import JSZip from 'jszip'
import { fixture, tobacco, decodedPixelSignature } from './fixtures'

const base = '/api/gallery/v1'
const origin = 'http://127.0.0.1:43928'
const admin = { Origin: origin, 'X-Gallery-Test-Admin': 'reviewer-fixture' }

test('real local Worker rejects changed bytes and keeps approved downloads revocable', async ({ request }) => {
  test.setTimeout(150000)
  const f = await fixture(2048), key = randomBytes(32).toString('hex')
  const headers = { Origin: origin, Authorization: `Bearer ${key}`, 'X-Turnstile-Token': 'local-turnstile-token' }
  const create = await request.post(`${base}/submissions`, { headers, data: f.draft })
  expect(create.status(), await create.text()).toBe(201)
  expect((await request.get(`${base}/submissions/${f.draft.submissionId}`, {headers})).status()).toBe(404)
  expect((await request.get(`${base}/submissions/${f.draft.submissionId}/preview`, {headers})).status()).toBe(404)
  expect((await request.post(`${base}/submissions/${f.draft.submissionId}/withdraw`, {headers})).status()).toBe(404)
  expect((await request.get(`${base}/admin/submissions`)).status()).toBe(403)
  expect((await request.get(`${base}/labels/${f.draft.submissionId}/artwork`)).status()).toBe(404)
  const swapped = await fixture(2048, 1)
  const mismatch = await request.put(`${base}/submissions/${f.draft.submissionId}/artwork`, { headers: { ...headers, 'Content-Type': 'image/png' }, data: swapped.png })
  expect(mismatch.status()).toBe(400)
  expect(await mismatch.json()).toMatchObject({ error: 'image_mismatch' })
  const upload = await request.put(`${base}/submissions/${f.draft.submissionId}/artwork`, { headers: { ...headers, 'Content-Type': 'image/png' }, data: f.png })
  expect(upload.status(), await upload.text()).toBe(200)
  const pending = await upload.json()
  expect(pending.state).toBe('pending')
  expect((await request.post(`${base}/submissions`, { headers, data: f.draft })).status()).toBe(200)
  expect((await request.post(`${base}/admin/submissions/${pending.id}/approve`, { headers: admin, data: { expectedVersion: pending.version, digest: 'wrong' } })).status()).toBe(409)
  const approval = await request.post(`${base}/admin/submissions/${pending.id}/approve`, { headers: admin, data: { expectedVersion: pending.version, digest: pending.digest } })
  expect(approval.status(), await approval.text()).toBe(200)
  let approved = await approval.json()
  const png = await request.get(`${base}/labels/${pending.id}/artwork`)
  expect(png.status()).toBe(200); expect(png.headers()['cache-control']).toBe('public, max-age=0, must-revalidate')
  const bytes = await png.body()
  expect(decodedPixelSignature(bytes)).toEqual(decodedPixelSignature(f.png))
  const download = await request.get(`${base}/labels/${pending.id}/pack`)
  const pack = await JSZip.loadAsync(await download.body())
  const manifest = JSON.parse(await pack.file('manifest.json')!.async('string'))
  expect(manifest.assets.artwork.sha256).toBe(createHash('sha256').update(bytes).digest('hex'))
  expect(await pack.file('artwork/label.png')!.async('nodebuffer')).toEqual(bytes)
  expect(JSON.stringify(manifest)).not.toContain('PRIVATE_')
  const projection = await request.get(`${base}/labels/${pending.id}`)
  const data = await projection.json()
  for (const field of ['capability_hash', 'proposedIdentity', 'acknowledgement', 'r2_key', 'reviewer']) expect(JSON.stringify(data)).not.toContain(field)
  const unpublished = await request.post(`${base}/admin/publications/${pending.id}/unpublish`, { headers: admin, data: { expectedVersion: approved.version } })
  expect(unpublished.status()).toBe(200); approved = await unpublished.json()
  await expect.poll(async () => Promise.all(['', '/thumbnail', '/artwork', '/pack'].map(async suffix =>
    (await request.get(`${base}/labels/${pending.id}${suffix}`, { headers: { 'If-None-Match': '*' } })).status()
  )), { timeout: 90000, intervals: [1000, 2000, 5000] }).toEqual([404, 404, 404, 404])
  const republished=await request.post(`${base}/admin/publications/${pending.id}/republish`, {headers:admin,data:{expectedVersion:approved.version}})
  expect(republished.status()).toBe(200)
  approved=await republished.json()
  expect((await request.post(`${base}/admin/publications/${pending.id}/unpublish`,{headers:admin,data:{expectedVersion:approved.version}})).status()).toBe(200)
  for (const suffix of ['/thumbnail', '/artwork', '/pack']) expect((await request.get(`${base}/labels/${pending.id}${suffix}`)).status()).toBe(404)
  const future = new Date(Date.now() + 31 * 86400000).toISOString()
  const cleanup = await request.get(`/__test/cleanup?now=${encodeURIComponent(future)}`, { headers: admin })
  expect(cleanup.status(), await cleanup.text()).toBe(200)
  const cleanupResult = await cleanup.json()
  expect(cleanupResult.failures).toBe(0)
  expect(cleanupResult.deleted).toBeGreaterThanOrEqual(1)
  expect((await (await request.get(`${base}/admin/submissions/${pending.id}`, { headers:admin })).json()).state).toBe('deleted')
})

test('browser selects artwork, submits privately, reviewer publishes, public user imports and prints', async ({ page, browser, request }) => {
  const f = await fixture(1024, 2)
  const writes: { path: string; body: string | null }[] = []
  page.on('request', req => { if (['POST', 'PUT'].includes(req.method())) writes.push({ path: new URL(req.url()).pathname, body: req.method() === 'POST' ? req.postData() : null }) })
  await page.route('https://challenges.cloudflare.com/turnstile/v0/api.js*', route => route.fulfill({ contentType: 'application/javascript', body: 'window.turnstile={render:function(e,o){setTimeout(function(){o.callback("local-turnstile-token")},10);return "fixture"},remove:function(){},reset:function(){}};' }))
  await page.goto('/labels/print')
  await page.getByLabel('Label ZIP').setInputFiles({ name: 'original.cellarpack.zip', mimeType: 'application/zip', buffer: f.zip })
  await page.getByRole('button', { name: /^Add \d+ labels?$/ }).click()
  await expect(page.getByRole('heading', { name: 'Share your labels' })).toBeVisible()
  expect(writes.filter(w => w.path.startsWith(base))).toEqual([])
  await page.getByLabel(`Share ${tobacco.maker} ${tobacco.blend}`, { exact: true }).check()
  expect(writes.filter(w => w.path.startsWith(base))).toEqual([])
  await page.getByLabel('I created or generated these labels', { exact: false }).check()
  await page.getByRole('button', { name: 'Submit for review', exact: true }).click()
  await expect(page.getByText('Submitted for review. Your label will appear in the gallery once approved.', { exact: true })).toBeVisible()
  const creation = writes.find(w => w.path === `${base}/submissions`)!
  expect(creation).toBeTruthy(); expect(creation.body).not.toContain('PRIVATE_')
  const id = JSON.parse(creation.body!).submissionId
  await expect(page.getByRole('link', {name:'Private status and withdrawal link'})).toHaveCount(0)
  expect((await request.get(`${base}/labels/${id}/pack`)).status()).toBe(404)
  await page.screenshot({ path: 'output/gallery/gallery-private-submission.png', fullPage: true })
  const reviewContext = await browser.newContext({ extraHTTPHeaders: { 'X-Gallery-Test-Admin': 'reviewer-fixture' } })
  const reviewer = await reviewContext.newPage()
  await reviewer.goto(`${origin}/admin/gallery`)
  await reviewer.getByRole('button', { name: new RegExp(tobacco.blend) }).first().click()
  await expect(reviewer.locator('.gallery-review-art')).toBeVisible()
  await reviewer.getByLabel('I reviewed this artwork and the saved details', { exact: false }).check()
  await reviewer.getByRole('button', { name: 'Approve and publish' }).click()
  await expect(reviewer.getByRole('button', { name: 'Unpublish now' })).toBeVisible()
  await reviewer.screenshot({ path: 'output/gallery/gallery-review-approved.png', fullPage: true })
  const publicContext = await browser.newContext()
  const publicPage = await publicContext.newPage()
  publicPage.on('request', req => { if (['POST', 'PUT'].includes(req.method())) writes.push({ path: new URL(req.url()).pathname, body: req.method() === 'POST' ? req.postData() : null }) })
  await publicPage.goto(`${origin}/gallery`)
  const search = publicPage.getByRole('combobox', { name: 'Maker or blend', exact: true })
  await search.fill(`${tobacco.maker} ${tobacco.blend}`)
  await search.press('ArrowDown'); await search.press('Enter')
  await expect(publicPage.getByRole('button', { name: 'Add to your labels' }).first()).toBeVisible()
  expect((await new AxeBuilder({ page: publicPage }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await publicPage.screenshot({ path: 'output/gallery/gallery-public-library.png', fullPage: true })
  const previous = writes.length
  await publicPage.getByRole('button', { name: 'Add to your labels' }).first().click()
  await expect(publicPage.getByRole('button', { name: 'Added to your labels' })).toBeVisible()
  await publicPage.getByRole('button', { name: 'Review & print' }).click()
  await expect(publicPage.getByRole('heading', { name: 'Your labels' })).toBeVisible()
  await expect(publicPage.getByRole('heading', { name: 'Share your labels' })).toHaveCount(0)
  const addedWrites = writes.slice(previous)
  expect(addedWrites.filter(write => write.path !== '/api/analytics/v1/print-intent')).toEqual([])
  for (const write of addedWrites) {
    const event = JSON.parse(write.body!)
    expect(Object.keys(event).sort()).toEqual(['event', 'labels'])
    expect(['added-to-labels', 'selected-for-print']).toContain(event.event)
    expect(write.body).not.toContain('PRIVATE_')
  }
  await publicPage.emulateMedia({ media: 'print' })
  await publicPage.pdf({ path: 'output/gallery/gallery-print.pdf', format: 'Letter', printBackground: true })
  await publicPage.emulateMedia({ media: 'screen' })
  await reviewer.getByRole('button', {name:'Unpublish now'}).click()
  await expect(reviewer.getByRole('button', {name:'Republish reviewed version'})).toBeVisible()
  expect((await request.get(`${base}/labels/${id}/pack`)).status()).toBe(404)
  await reviewContext.close()
  await publicContext.close()
})
