// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { webcrypto } from 'node:crypto'
import { Blob as NodeBlob } from 'node:buffer'
import { IDBFactory, IDBObjectStore } from 'fake-indexeddb'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App, { GalleryAdminShell } from './App'
import { collectionFixture } from './lib/collection/test-fixtures'
import { createCollectionStore, updateRow } from './lib/collection'
import type { CellarPackImportResult } from './lib/cellarpack/types'
const { importer } = vi.hoisted(() => ({ importer: vi.fn() }))
vi.mock('./lib/cellarpack', () => ({ importCellarPack: importer }))
let fixture: CellarPackImportResult
const imported = (id: string, shape = 'circle') => {
  const item = structuredClone(fixture.labels[0])
  item.artwork.data = Uint8Array.from(new Uint8Array(item.artwork.data)).buffer
  item.id = id.toLowerCase().replace(/[^a-z0-9]+/g, '-'); item.label.id = item.id; item.label.maker = 'Test Maker'; item.label.blend = id
  item.label.surface.shape = shape as typeof item.label.surface.shape
  return item
}
const ready = (items = [imported('Blend A')]) => ({ ...fixture, status: 'ready' as const, manifest: { ...fixture.manifest!, title: 'Test pack', labels: items.map(item => item.label) }, labels: items, issues: [], quarantinedLabels: [] })
async function upload(review = false) {
  await waitFor(() => expect(screen.getByLabelText('Label ZIP')).toBeEnabled())
  const file = new File(['zip'], 'labels.zip', { type: 'application/zip' })
  Object.defineProperty(file, 'arrayBuffer', { value: async () => new ArrayBuffer(1) })
  fireEvent.change(screen.getByLabelText('Label ZIP'), { target: { files: [file] } })
  if (review) return
  await waitFor(() => expect(screen.getByLabelText('Label ZIP')).toBeEnabled())
  const accept = screen.queryByRole('button', { name: /^Add \d+ labels?$|Keep current labels/ })
  if (accept) { fireEvent.click(accept); await waitFor(() => expect(screen.getByLabelText('Label ZIP')).toBeEnabled()) }
}
async function addBlend(name: string) {
  const input = screen.getByRole('combobox', { name: 'Add a blend' })
  await waitFor(() => expect(input).not.toHaveAttribute('readonly'))
  fireEvent.change(input, { target: { value: name } })
  fireEvent.click(screen.getByRole('button', { name: 'Add blend' }))
  await waitFor(() => {
    const error = screen.queryByRole('alert')
    if (error) throw new Error(error.textContent ?? 'Saving failed')
    expect(screen.getByRole('heading', { name })).toBeInTheDocument()
  })
  await waitFor(() => expect(input).not.toHaveAttribute('readonly'))
}
async function savedCollection() {
  const store = createCollectionStore()
  try { return await store.load() } finally { store.close() }
}
beforeEach(async () => {
  vi.stubGlobal('crypto', webcrypto)
  vi.stubGlobal('Blob', NodeBlob)
  vi.stubGlobal('indexedDB', new IDBFactory())
  vi.stubGlobal('BroadcastChannel', undefined)
  vi.stubGlobal('fetch', vi.fn(async input => String(input) === '/api/gallery/v1/config' ? Response.json({ intake: false, serving: false }) : Response.json({ status: 'collected', sources: [] })))
  fixture = await collectionFixture()
  expect(fixture.status, JSON.stringify(fixture.issues)).toBe('ready')
  sessionStorage.clear()
  window.history.replaceState({}, '', '/labels/create')
  importer.mockReset()
  window.scrollTo = vi.fn()
  Element.prototype.scrollIntoView = vi.fn()
  Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:label') })
  Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() })
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: vi.fn().mockResolvedValue(undefined) } })
})
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
describe('home, prompt, print, and help navigation', () => {
  it('starts on the landing page and keeps committed labels when returning through home', async () => {
    window.history.replaceState({}, '', '/labels')
    render(<App />)
    expect(screen.getByRole('heading', { name: 'Make the jar look like the tin.' })).toBeInTheDocument()
    expect(screen.queryByRole('combobox', { name: 'Tobaccos' })).not.toBeInTheDocument()
    expect(importer).not.toHaveBeenCalled()
    const workflow = within(screen.getByRole('navigation', { name: 'Workflow' }))
    expect(workflow.getAllByRole('link').map(link => link.textContent)).toEqual(['Choose labels', 'Print labels'])
    expect(workflow.queryByRole('link', { name: 'Labels' })).not.toBeInTheDocument()
    expect(screen.getByText('No AI chat is needed to print existing designs.', { exact: false })).toBeInTheDocument()
    expect(screen.getByText('Optional', { exact: true })).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Workflow' })).getByRole('link', { name: 'Choose labels' }))
    await addBlend('Escudo')
    fireEvent.click(screen.getByRole('link', { name: 'Tin to Cellar home' }))
    expect(window.location.pathname).toBe('/labels')
    fireEvent.click(within(screen.getByRole('main')).getByRole('button', { name: 'Choose labels' }))
    expect(screen.getByRole('main')).toHaveFocus()
    expect(window.scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0 })
    expect(screen.getByRole('heading', { name: 'Escudo' })).toBeInTheDocument()
    expect((await savedCollection())?.rows[0].blend).toBe('Escudo')
  })
  it('opens ZIP import directly from home without starting a creation request', () => {
    window.history.replaceState({}, '', '/labels')
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Import a label ZIP' }))
    expect(window.location.pathname).toBe('/labels/print')
    expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Copy prompt/ })).not.toBeInTheDocument()
    expect(importer).not.toHaveBeenCalled()
  })
  it('offers reload for a stale code download without asking AI to repair the ZIP', async () => {
    window.history.replaceState({}, '', '/labels/print')
    importer.mockRejectedValue(new TypeError('Failed to fetch dynamically imported module: https://example.com/assets/old.js'))
    render(<App />)
    await upload()
    expect(await screen.findByRole('alert')).toHaveTextContent('The label reader couldn’t load')
    expect(screen.getByRole('button', { name: 'Reload app' })).toBeEnabled()
    expect(screen.queryByRole('button', { name: 'Copy repair request' })).not.toBeInTheDocument()
    expect(screen.queryByText('ZIP needs repair')).not.toBeInTheDocument()
  })
  it('requires committed creation targets and saves the exact prompt before copying', async () => {
    render(<App />)
    const input = screen.getByRole('combobox', { name: 'Add a blend' })
    await waitFor(() => expect(input).not.toHaveAttribute('readonly'))
    fireEvent.change(input, { target: { value: 'Unlisted Family Tobacco' } })
    expect(screen.queryByRole('button', { name: /Copy prompt/ })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Add blend' }))
    await screen.findByRole('heading', { name: 'Unlisted Family Tobacco' })
    expect(screen.queryByRole('button', { name: /Copy prompt/ })).not.toBeInTheDocument()
    await waitFor(() => expect(screen.getByRole('button', { name: 'Create my own' })).toBeEnabled())
    fireEvent.click(screen.getByRole('button', { name: 'Create my own' }))
    const copy = await screen.findByRole('button', { name: 'Copy prompt for 1 label' })
    await waitFor(() => expect(copy).toBeEnabled())
    fireEvent.click(copy)
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining('Unlisted Family Tobacco')))
    expect((await savedCollection())?.handoff?.prompt).toBe(vi.mocked(navigator.clipboard.writeText).mock.calls[0][0])
  })
  it('returns to the landing page when browser Back restores the initial label URL', async () => {
    window.history.replaceState({}, '', '/labels')
    render(<App />)
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Workflow' })).getByRole('link', { name: 'Choose labels' }))
    window.history.back()
    await waitFor(() => expect(screen.getByRole('heading', { name: 'Make the jar look like the tin.' })).toBeInTheDocument())
    expect(window.location.pathname).toBe('/labels')
    expect(screen.getByRole('main')).toHaveFocus()
    expect(window.scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0 })
  })
  it('keeps the current view and committed work when following the skip link', async () => {
    render(<App />)
    await addBlend('Keep this blend')
    vi.mocked(window.scrollTo).mockClear()
    fireEvent.click(screen.getByRole('link', { name: 'Skip to main content' }))
    expect(screen.getByRole('heading', { name: 'Keep this blend' })).toBeInTheDocument()
    expect(screen.getByRole('main')).toHaveFocus()
    expect(window.scrollTo).not.toHaveBeenCalled()
  })
  it('opens a direct print path without importing or fetching a file', () => {
    window.history.replaceState({}, '', '/labels/print')
    render(<App />)
    expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'Print labels' })).toHaveAttribute('aria-current', 'page')
    expect(importer).not.toHaveBeenCalled()
  })
  it('honors back and forward navigation and shows a missing page for unknown paths', async () => {
    render(<App />)
    await addBlend('Escudo')
    fireEvent.click(screen.getByRole('link', { name: 'How it works' }))
    expect(window.location.pathname).toBe('/labels/help')
    fireEvent.click(screen.getByRole('link', { name: 'Print labels' }))
    expect(window.location.pathname).toBe('/labels/print')
    window.history.back()
    await waitFor(() => expect(screen.getByRole('heading', { name: 'How it works' })).toBeInTheDocument())
    window.history.forward()
    await waitFor(() => expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument())
    window.history.replaceState({}, '', '/unknown')
    fireEvent(window, new PopStateEvent('popstate'))
    expect(screen.getByRole('heading', { name: 'Page not found' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('link', { name: 'Go to Labels' }))
    fireEvent.click(screen.getByRole('link', { name: 'Choose labels' }))
    expect(screen.getByRole('heading', { name: 'Escudo' })).toBeInTheDocument()
  })
  it('downloads complete reusable instructions with a local return link', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: 'How it works' }))
    const download = screen.getByRole('link', { name: 'Download instructions' })
    expect(download).toHaveAttribute('download', 'tin-to-cellar-instructions.md')
    expect(download).toHaveAttribute('href', 'blob:label')
    const blob = vi.mocked(URL.createObjectURL).mock.calls[0][0] as Blob
    const contents = await blob.text()
    expect(contents).toContain('tin-to-cellar/cellarpack')
    expect(contents).toContain(`${window.location.origin}/labels/print`)
    expect(URL.revokeObjectURL).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('link', { name: 'Choose labels' }))
    expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:label')
  })
  it('opens preparation directly and keeps the workflow explanation in its own view', async () => {
    render(<App />)
    expect(screen.getByRole('combobox', { name: 'Add a blend' })).toBeInTheDocument()
    expect(screen.getByRole('contentinfo')).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'How it works' })).not.toBeInTheDocument()
    await addBlend('Escudo')
    fireEvent.click(screen.getByRole('link', { name: 'How it works' }))
    expect(screen.getByRole('heading', { name: 'How it works' })).toBeInTheDocument()
    expect(screen.getByText(/account you already have/)).toBeInTheDocument()
    expect(screen.queryByText(/reloading or closing the page clears/)).not.toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'How it works' })).toHaveAttribute('aria-current', 'page')
    fireEvent.click(screen.getByRole('link', { name: 'Choose labels' }))
    expect(screen.getByRole('heading', { name: 'Escudo' })).toBeInTheDocument()
  })
  it('preserves paper position, alignment, and preview page when switching screens', async () => {
    importer.mockResolvedValue(ready())
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload()
    fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '10' } })
    await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(10))
    fireEvent.change(screen.getByLabelText('Start at slot'), { target: { value: '2' } })
    await waitFor(() => expect(screen.getByLabelText('Start at slot')).toHaveValue('2'))
    fireEvent.change(screen.getByLabelText('Horizontal adjustment'), { target: { value: '.05' } })
    await waitFor(() => expect(screen.getByLabelText('Horizontal adjustment')).toHaveValue(.05))
    fireEvent.change(screen.getByLabelText('Vertical adjustment'), { target: { value: '-.03' } })
    await waitFor(() => expect(screen.getByLabelText('Vertical adjustment')).toHaveValue(-.03))
    fireEvent.click(screen.getByRole('button', { name: 'Next sheet' }))
    await screen.findByText('Sheet 2 of 2')
    fireEvent.click(screen.getByRole('link', { name: /Choose labels/i }))
    fireEvent.click(screen.getByRole('link', { name: 'How it works' }))
    fireEvent.click(screen.getByRole('link', { name: 'Tin to Cellar home' }))
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    expect(screen.getByLabelText('Start at slot')).toHaveValue('2')
    expect(screen.getByLabelText('Horizontal adjustment')).toHaveValue(.05)
    expect(screen.getByLabelText('Vertical adjustment')).toHaveValue(-.03)
    expect(screen.getByText('Sheet 2 of 2')).toBeInTheDocument()
    expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(10)
  })
  it('offers repair for a partial archive even when every label can print', async () => {
    importer.mockResolvedValue({ ...ready(), status: 'partial', issues: [{ severity: 'error', code: 'INVALID_SHEET_PROFILE', message: 'The extra sheet profile is invalid.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload()
    expect(await screen.findByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.getByRole('button', { name: 'Copy repair request' })).toBeInTheDocument()
  })
  it('keeps ordinary warnings informational instead of requesting repair', async () => {
    importer.mockResolvedValue({ ...ready(), issues: [{ severity: 'warning', code: 'LIMITED_RESEARCH', message: 'Research was limited.' }, { severity: 'warning', code: 'MISSING_PREVIEW', message: 'Optional preview is missing.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload()
    expect(await screen.findByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.queryByRole('button', { name: 'Copy repair request' })).not.toBeInTheDocument()
    expect(screen.queryByText('Optional preview is missing.')).not.toBeInTheDocument()
    expect(screen.getByText('Research was limited.')).toBeInTheDocument()
  })
  it('reviews valid additions before saving them into quantity and print controls', async () => {
    importer.mockResolvedValue(ready())
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload(true)
    const add = await screen.findByRole('button', { name: 'Add 1 label' })
    expect(screen.queryByLabelText('Quantity for Blend A')).not.toBeInTheDocument()
    expect((await savedCollection())?.rows ?? []).toHaveLength(0)
    await waitFor(() => expect(add).toBeEnabled())
    fireEvent.click(add)
    await waitFor(() => {
      expect(screen.queryByRole('alert')?.textContent ?? '').toBe('')
      expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(1)
    })
    expect(screen.getByRole('button', { name: 'Print 1 label' })).toBeInTheDocument()
    expect(screen.queryByText('Compose the sheet')).not.toBeInTheDocument()
  })
  it('preserves existing labels, quantities and prior receipts when an additional ZIP is rejected', async () => {
    importer.mockResolvedValueOnce(ready()).mockResolvedValueOnce({ ...ready([]), manifest: null, status: 'rejected', labels: [], quarantinedLabels: [], issues: [{ severity: 'fatal', code: 'INVALID_MANIFEST_SCHEMA', message: 'Manifest is missing artworkAssetId.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload()
    fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '3' } })
    await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3))
    vi.mocked(URL.revokeObjectURL).mockClear()
    await upload()
    await screen.findByRole('button', { name: 'Copy repair request' })
    expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3)
    expect(URL.revokeObjectURL).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Copy repair request' }))
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalled())
    expect(vi.mocked(navigator.clipboard.writeText).mock.calls[0][0]).toContain('artworkAssetId')
    expect(await screen.findByText(/Paste this into the same AI chat/)).toBeInTheDocument()
    expect((await savedCollection())?.receipts).toHaveLength(2)
  })
  it('keeps incompatible artwork off the printed sheet and provides repair instructions', async () => {
    importer.mockResolvedValue(ready([imported('Round'), imported('Square', 'square')]))
    render(<App />)
    fireEvent.click(screen.getByRole('link', { name: /Print labels/i }))
    await upload()
    expect(await screen.findByLabelText('Quantity for Round')).toHaveValue(1)
    expect(screen.queryByLabelText('Quantity for Square')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Copy repair request' })).toBeInTheDocument()
    expect(screen.getAllByText(/does not match this sheet/).length).toBeGreaterThan(0)
  })
})

it('preserves feedback from its original pack when a later import throws', async () => {
  window.history.replaceState({}, '', '/labels/print')
  const feedback = {
    format: 'tin-to-cellar/feedback', schemaVersion: '1.0.0', promptVersion: '2026-09-06.1',
    request: { labelCount: 1, shape: 'circle' }, outcome: 'complete', steps: [], issues: [],
  }
  importer.mockResolvedValueOnce({ ...ready(), manifest: { ...ready().manifest, extensions: { 'tin-to-cellar:feedback': feedback } } })
  render(<App />)
  await upload()
  expect(await screen.findByRole('button', { name: 'View shared diagnostics' })).toBeInTheDocument()
  expect(screen.queryByText('AI reported: Completed')).not.toBeInTheDocument()
  await waitFor(async () => expect((await savedCollection())?.receipts[0].delivery).toBe('sent'))
  importer.mockRejectedValueOnce(new Error('Invalid ZIP'))
  await upload()
  await screen.findByRole('alert')
  expect(screen.getByRole('button', { name: 'View shared diagnostics' })).toBeInTheDocument()
  expect((await savedCollection())?.receipts[0].contribution?.feedback).toEqual(feedback)
  expect(screen.queryByText('AI run details')).not.toBeInTheDocument()
})


it('opens the privacy page from the footer and directly by path', async () => {
  window.history.replaceState({}, '', '/labels')
  const { unmount } = render(<App />)
  fireEvent.click(screen.getByRole('link', { name: 'Privacy' }))
  expect(screen.getByRole('heading', { name: 'Privacy', level: 1 })).toBeInTheDocument()
  expect(screen.getByText(/automatically sends its valid AI feedback/)).toBeInTheDocument()
  unmount()
  window.history.replaceState({}, '', '/privacy')
  render(<App />)
  expect(screen.getByRole('heading', { name: 'Privacy', level: 1 })).toBeInTheDocument()
})

it('collects valid diagnostics from a readable manifest even when its artwork is rejected', async () => {
  window.history.replaceState({}, '', '/labels/print')
  const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json({ status: 'collected' }))
  const feedback = { format: 'tin-to-cellar/feedback', schemaVersion: '1.0.0', promptVersion: '2026-09-06.1', request: { labelCount: 1, shape: 'circle' }, outcome: 'failed', steps: [], issues: [] }
  importer.mockResolvedValueOnce({ ...ready([]), status: 'rejected', manifest: { ...ready([]).manifest, extensions: { 'tin-to-cellar:feedback': feedback } } })
  render(<App />)
  await upload()
  await waitFor(() => expect(fetchMock).toHaveBeenCalledWith('/api/labels/contributions', expect.objectContaining({ method: 'POST' })))
  const payload = JSON.parse(fetchMock.mock.calls.find(([url]) => url === '/api/labels/contributions')![1]!.body as string)
  expect(payload.feedback.outcome).toBe('failed')
  expect(payload.submissionId).toMatch(/^[a-f0-9]{64}$/)
  expect(payload).not.toHaveProperty('manifest')
  fetchMock.mockRestore()
})

it('redirects the site root to Labels using real links', () => {
  window.history.replaceState({}, '', '/')
  render(<App />)
  expect(screen.getByRole('link', { name: 'Privacy' })).toHaveAttribute('href', '/privacy')
  expect(window.location.pathname).toBe('/labels')
  expect(screen.getByRole('heading', { name: 'Make the jar look like the tin.' })).toBeInTheDocument()
  expect(screen.getByRole('link', { name: 'Print labels' })).toHaveAttribute('href', '/labels/print')
})

it('preserves imported artwork and quantities when Back returns from the site home', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValue(ready())
  render(<App />)
  await upload()
  fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '4' } })
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(4))
  vi.mocked(URL.revokeObjectURL).mockClear()
  fireEvent.click(screen.getByRole('link', { name: 'Tin to Cellar home' }))
  window.history.back()
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(4))
  expect(URL.revokeObjectURL).not.toHaveBeenCalled()
  expect(importer).toHaveBeenCalledTimes(1)
})


it('opens import privacy details without discarding the imported pack', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValue(ready())
  render(<App />)
  await upload()
  fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '6' } })
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(6))
  vi.mocked(URL.revokeObjectURL).mockClear()
  fireEvent.click(screen.getByRole('link', { name: 'Privacy details' }))
  expect(window.location.pathname).toBe('/privacy')
  expect(screen.getByRole('heading', { name: 'Privacy', level: 1 })).toBeInTheDocument()
  window.history.back()
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(6))
  expect(URL.revokeObjectURL).not.toHaveBeenCalled()
})

it('adds trusted examples without collecting their diagnostics or erasing prior local work', async () => {
  window.history.replaceState({}, '', '/labels/print')
  const feedback = { format: 'tin-to-cellar/feedback', schemaVersion: '0.2.0', protocolRevision: '0.0.20', request: { labelCount: 1, shape: 'circle' }, outcome: 'complete', steps: [], issues: [] }
  const retrospective = { format: 'tin-to-cellar/retrospective', schemaVersion: '0.1.0', protocolRevision: '0.0.20', capabilities: {}, tools: [], observations: [{ stage: 'proof', kind: 'helped', explanation: 'Prior private process note' }] }
  const manifest = { ...ready().manifest, title: 'Ordinary pack', extensions: { 'tin-to-cellar:protocol': { revision: '0.0.20', cellarpackVersion: '0.1.0', feedbackVersion: '0.2.0' }, 'tin-to-cellar:feedback': feedback, 'tin-to-cellar:retrospective': retrospective } }
  importer.mockResolvedValueOnce({ ...ready(), manifest }).mockResolvedValueOnce({ ...ready([imported('Demo blend')]), manifest: { ...manifest, title: 'Trusted example' } })
  const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async input => {
    if (String(input) === '/api/gallery/v1/config') return Response.json({ intake: true, serving: true, turnstileSiteKey: 'test', noticeVersion: '2026-09-06-v2' })
    if (String(input).startsWith('/examples/ten-blends/pack-')) return new Response(new Uint8Array([1]))
    return Response.json({ status: 'collected' })
  })
  const oldArrayBuffer = Object.getOwnPropertyDescriptor(File.prototype, 'arrayBuffer')
  const oldShowModal = Object.getOwnPropertyDescriptor(HTMLDialogElement.prototype, 'showModal')
  Object.defineProperty(File.prototype, 'arrayBuffer', { configurable: true, value: async () => new ArrayBuffer(1) })
  Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function (this: HTMLDialogElement) { this.setAttribute('open', '') } })
  try {
    render(<App />)
    await upload()
    await screen.findByRole('heading', { name: 'Share your labels' })
    fireEvent.click(await screen.findByRole('button', { name: 'View shared diagnostics' }))
    expect(screen.getByText(/Prior private process note/)).toBeInTheDocument()
    await waitFor(() => expect(fetchMock.mock.calls.filter(([url, init]) => url === '/api/labels/contributions' && init?.method === 'POST')).toHaveLength(1))
    fireEvent.click(screen.getByRole('link', { name: 'Tin to Cellar home' }))
    fireEvent.click(screen.getByRole('button', { name: 'Try the example pack' }))
    const add = await screen.findByRole('button', { name: 'Add 1 label' })
    await waitFor(() => expect(add).toBeEnabled())
    fireEvent.click(add)
    await screen.findByLabelText('Quantity for Demo blend')
    expect(importer).toHaveBeenCalledTimes(2)
    expect(fetchMock.mock.calls.filter(([url, init]) => url === '/api/labels/contributions' && init?.method === 'POST')).toHaveLength(1)
    expect(fetchMock.mock.calls.some(([url]) => url === '/api/labels/process-notes')).toBe(false)
    expect(screen.queryByRole('button', { name: 'View shared diagnostics' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Share process notes' })).not.toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Share your labels' })).toBeInTheDocument()
    expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.getByRole('button', { name: 'Print 2 labels' })).toBeEnabled()
    const saved = await savedCollection()
    expect(saved?.receipts).toHaveLength(2)
    expect(saved?.receipts[0].contribution?.feedback).toEqual(feedback)
    expect(saved?.receipts[1].contribution).toBe(null)
    expect(JSON.stringify(saved)).not.toContain('Prior private process note')
  } finally {
    fetchMock.mockRestore()
    if (oldArrayBuffer) Object.defineProperty(File.prototype, 'arrayBuffer', oldArrayBuffer); else Reflect.deleteProperty(File.prototype, 'arrayBuffer')
    if (oldShowModal) Object.defineProperty(HTMLDialogElement.prototype, 'showModal', oldShowModal); else Reflect.deleteProperty(HTMLDialogElement.prototype, 'showModal')
  }
})

it('renders a dedicated review shell with explicit public-site links and no contributor workflow', async () => {
 const fetcher=vi.fn(async(_input: RequestInfo | URL)=>Response.json({submissions:[],nextCursor:null}))
 vi.stubGlobal('fetch',fetcher)
 try {
  render(<GalleryAdminShell hostname="admin.tintocellar.com" />)
  expect(screen.getByRole('link',{name:'Open public site'})).toHaveAttribute('href','https://tintocellar.com/')
  expect(screen.queryByRole('navigation',{name:'Workflow'})).not.toBeInTheDocument();expect(screen.queryByText('Make a prompt')).not.toBeInTheDocument()
  await waitFor(()=>expect(fetcher).toHaveBeenCalled())
  expect(fetcher.mock.calls.every(call=>String(call[0]).startsWith('/api/gallery/v1/admin/'))).toBe(true)
 } finally { cleanup();vi.unstubAllGlobals() }
})
it('retires contributor status navigation without using old private-link fragments', async () => {
  const fetcher = vi.fn(async (_input: RequestInfo | URL) => Response.json({ intake: false, serving: false }))
  vi.stubGlobal('fetch', fetcher)
  try {
    window.history.replaceState({}, '', '/gallery/status#id=old-submission&key=old-private-value')
    render(<App />)
    expect(screen.getByRole('heading', { name: 'Page not found' })).toBeInTheDocument()
    await waitFor(() => expect(screen.getByRole('main')).toBeInTheDocument())
    expect(fetcher.mock.calls.some(call => /submissions|old-private-value/.test(String(call[0])))).toBe(false)
    expect(screen.queryByRole('button', { name: /withdraw/i })).not.toBeInTheDocument()
  } finally { cleanup(); vi.unstubAllGlobals() }
})

it('restores mixed ready and pending work after reload without replaying diagnostic submissions', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValueOnce(ready()).mockResolvedValueOnce(ready([imported('Blend B')]))
  const initial = render(<App />)
  await upload()
  fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '4' } })
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(4))
  await upload()
  await screen.findByLabelText('Quantity for Blend B')
  expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(4)
  expect(screen.getByRole('button', { name: 'Print 5 labels' })).toBeEnabled()
  fireEvent.click(screen.getByRole('link', { name: 'Choose labels' }))
  await addBlend('Still awaiting artwork')
  const beforeReload = await savedCollection()
  expect(beforeReload?.rows).toHaveLength(3)
  await waitFor(async () => expect((await savedCollection())?.receipts.every(receipt => receipt.delivery === 'sent')).toBe(true))
  initial.unmount()
  vi.mocked(fetch).mockClear()
  window.history.replaceState({}, '', '/labels/print')
  render(<App />)
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(4))
  expect(screen.getByLabelText('Quantity for Blend B')).toHaveValue(1)
  expect(screen.getByText(/1 labels still need artwork/)).toBeInTheDocument()
  expect(importer).toHaveBeenCalledTimes(2)
  expect(vi.mocked(fetch).mock.calls.some(([url]) => url === '/api/labels/contributions' || String(url).startsWith('https://example.com/fixture'))).toBe(false)
})

it('reimports an identical design without adding a row, increasing quantity, or resending diagnostics', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValue(ready())
  render(<App />)
  await upload()
  fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '3' } })
  await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3))
  await waitFor(async () => expect((await savedCollection())?.receipts[0].delivery).toBe('sent'))
  vi.mocked(fetch).mockClear()
  await upload()
  expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3)
  expect((await savedCollection())?.rows).toHaveLength(1)
  expect(vi.mocked(fetch).mock.calls.some(([url]) => url === '/api/labels/contributions')).toBe(false)
})

it('retains the previous collection and the import review when saving runs out of space', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValueOnce(ready()).mockResolvedValueOnce(ready([imported('Unsaved blend')]))
  render(<App />)
  await upload()
  await screen.findByLabelText('Quantity for Blend A')
  await waitFor(async () => expect((await savedCollection())?.receipts[0].delivery).toBe('sent'))
  await upload(true)
  const add = await screen.findByRole('button', { name: 'Add 1 label' })
  await waitFor(() => expect(add).toBeEnabled())
  const failedWrite = vi.spyOn(IDBObjectStore.prototype, 'put').mockImplementationOnce(() => { throw new DOMException('Full', 'QuotaExceededError') })
  fireEvent.click(add)
  await screen.findByRole('alert')
  failedWrite.mockRestore()
  expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(1)
  expect(screen.queryByLabelText('Quantity for Unsaved blend')).not.toBeInTheDocument()
  expect(screen.getByRole('heading', { name: 'Add your new labels' })).toBeInTheDocument()
  expect((await savedCollection())?.rows).toHaveLength(1)
})

it('does not replay a restored receipt when only manifest key order changes', async () => {
  window.history.replaceState({}, '', '/labels/print')
  const result = ready()
  importer.mockResolvedValue(result)
  const initial = render(<App />)
  await upload()
  await waitFor(async () => expect((await savedCollection())?.receipts[0].delivery).toBe('sent'))
  initial.unmount()
  vi.mocked(fetch).mockClear()
  importer.mockResolvedValue({ ...result, manifest: Object.fromEntries(Object.entries(result.manifest).reverse()) })
  render(<App />)
  await screen.findByLabelText('Quantity for Blend A')
  await upload()
  expect((await savedCollection())?.receipts).toHaveLength(1)
  expect(vi.mocked(fetch).mock.calls.some(([url]) => url === '/api/labels/contributions')).toBe(false)
})

it('preserves manual import choices for quantity changes and requires renewed review after artwork-request changes', async () => {
  window.history.replaceState({}, '', '/labels/print')
  importer.mockResolvedValueOnce(ready()).mockResolvedValueOnce(ready([imported('Blend B')]))
  render(<App />)
  await upload()
  await waitFor(async () => expect((await savedCollection())?.receipts[0].delivery).toBe('sent'))
  await upload(true)
  const choice = await screen.findByLabelText('How to add this design')
  fireEvent.change(choice, { target: { value: 'skip' } })
  const otherTab = createCollectionStore()
  try {
    let saved = (await otherTab.load())!
    saved = await otherTab.save(saved.revision, updateRow(saved, saved.rows[0].id, { quantity: 3 }))
    fireEvent(window, new Event('focus'))
    await waitFor(() => expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3))
    expect(choice).toHaveValue('skip')
    expect(screen.queryByRole('button', { name: 'Review updated choices' })).not.toBeInTheDocument()
    await otherTab.save(saved.revision, updateRow(saved, saved.rows[0].id, { notes: 'Different edition requested' }))
    fireEvent(window, new Event('focus'))
    const refresh = await screen.findByRole('button', { name: 'Review updated choices' })
    expect(screen.getByRole('button', { name: 'Add 1 label' })).toBeDisabled()
    expect(screen.queryByLabelText('Quantity for Blend B')).not.toBeInTheDocument()
    fireEvent.click(refresh)
    expect(screen.getByRole('button', { name: 'Add 1 label' })).toBeEnabled()
  } finally { otherTab.close() }
})
