// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
const { importer } = vi.hoisted(() => ({ importer: vi.fn() }))
vi.mock('./lib/cellarpack', () => ({ importCellarPack: importer }))
const imported = (id: string, shape = 'circle') => ({
  id, artwork: { data: new Uint8Array([1, 2, 3]), mediaType: 'image/png' }, issues: [],
  label: { id, maker: 'Test Maker', blend: id,
    surface: { shape, finishedSize: { width: 2.5, height: 2.5, unit: 'in' }, bleed: { top: .125, right: .125, bottom: .125, left: .125, unit: 'in' } },
    writeInAreas: [{ geometry: { x: .3, y: .7, width: .4, height: .1 }, overlay: { mode: 'blank' } }],
  },
})
const ready = (items = [imported('Blend A')]) => ({ status: 'ready', manifest: { title: 'Test pack' }, labels: items, issues: [], quarantinedLabels: [] })
function upload() {
  const file = new File(['zip'], 'labels.zip', { type: 'application/zip' })
  Object.defineProperty(file, 'arrayBuffer', { value: async () => new ArrayBuffer(1) })
  fireEvent.change(screen.getByLabelText('Label ZIP'), { target: { files: [file] } })
}
beforeEach(() => {
  window.history.replaceState({}, '', '/#create')
  importer.mockReset()
  window.scrollTo = vi.fn()
  Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:label') })
  Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() })
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: vi.fn().mockResolvedValue(undefined) } })
})
afterEach(cleanup)
describe('home, prompt, print, and help navigation', () => {
  it('starts on the landing page and keeps a label request when returning through home', () => {
    window.history.replaceState({}, '', '/')
    render(<App />)
    expect(screen.getByRole('heading', { name: 'Make the jar look like the tin.' })).toBeInTheDocument()
    expect(screen.queryByRole('combobox', { name: 'Tobaccos' })).not.toBeInTheDocument()
    expect(importer).not.toHaveBeenCalled()
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Workflow' })).getByRole('button', { name: 'Make a prompt' }))
    fireEvent.change(screen.getByRole('combobox', { name: 'Tobaccos' }), { target: { value: 'Escudo' } })
    fireEvent.change(screen.getByLabelText('Special requests'), { target: { value: 'Keep the crest' } })
    fireEvent.click(screen.getByRole('button', { name: 'Tin to Cellar home' }))
    expect(window.location.hash).toBe('#home')
    fireEvent.click(within(screen.getByRole('main')).getByRole('button', { name: 'Make a prompt' }))
    expect(screen.getByRole('main')).toHaveFocus()
    expect(window.scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0 })
    expect(screen.getByRole('button', { name: 'Remove Escudo' })).toBeInTheDocument()
    expect(screen.getByLabelText('Special requests')).toHaveValue('Keep the crest')
  })
  it('offers reload for a stale code download without asking AI to repair the ZIP', async () => {
    window.history.replaceState({}, '', '/#print')
    importer.mockRejectedValue(new TypeError('Failed to fetch dynamically imported module: https://example.com/assets/old.js'))
    render(<App />)
    upload()
    expect(await screen.findByRole('alert')).toHaveTextContent('The label reader couldn’t load')
    expect(screen.getByRole('button', { name: 'Reload app' })).toBeEnabled()
    expect(screen.queryByRole('button', { name: 'Copy repair request' })).not.toBeInTheDocument()
    expect(screen.queryByText('ZIP needs repair')).not.toBeInTheDocument()
  })
  it('includes an unfinished custom tobacco in Copy prompt without requiring Enter', async () => {
    render(<App />)
    fireEvent.change(screen.getByRole('combobox', { name: 'Tobaccos' }), { target: { value: 'Unlisted Family Tobacco' } })
    fireEvent.click(screen.getByRole('button', { name: 'Copy prompt' }))
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining('Unlisted Family Tobacco')))
  })
  it('returns to the landing page when browser Back restores the initial URL without a hash', async () => {
    window.history.replaceState({}, '', '/')
    render(<App />)
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Workflow' })).getByRole('button', { name: 'Make a prompt' }))
    window.history.back()
    await waitFor(() => expect(screen.getByRole('heading', { name: 'Make the jar look like the tin.' })).toBeInTheDocument())
    expect(window.location.hash).toBe('')
    expect(screen.getByRole('main')).toHaveFocus()
    expect(window.scrollTo).toHaveBeenLastCalledWith({ top: 0, left: 0 })
  })
  it('keeps the current view when following the skip link', () => {
    render(<App />)
    fireEvent.change(screen.getByLabelText('Special requests'), { target: { value: 'Keep the border' } })
    vi.mocked(window.scrollTo).mockClear()
    window.history.replaceState({}, '', '/#main-content')
    fireEvent(window, new Event('hashchange'))
    expect(screen.getByLabelText('Special requests')).toHaveValue('Keep the border')
    expect(window.scrollTo).not.toHaveBeenCalled()
  })
  it('opens a direct print hash without importing or fetching a file', () => {
    window.history.replaceState({}, '', '/#print')
    render(<App />)
    expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Print labels' })).toHaveAttribute('aria-current', 'page')
    expect(importer).not.toHaveBeenCalled()
  })
  it('honors back and forward navigation while ignoring unknown hashes', async () => {
    render(<App />)
    fireEvent.change(screen.getByLabelText('Tobaccos'), { target: { value: 'Escudo' } })
    fireEvent.click(screen.getByRole('button', { name: 'How it works' }))
    expect(window.location.hash).toBe('#help')
    fireEvent.click(screen.getByRole('button', { name: 'Print labels' }))
    expect(window.location.hash).toBe('#print')
    window.history.back()
    await waitFor(() => expect(screen.getByRole('heading', { name: 'How it works' })).toBeInTheDocument())
    window.history.forward()
    await waitFor(() => expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument())
    window.history.replaceState({}, '', '/#unknown')
    fireEvent(window, new Event('hashchange'))
    expect(screen.getByLabelText('Label ZIP')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Make a prompt' }))
    expect(screen.getByRole('button', { name: 'Remove Escudo' })).toBeInTheDocument()
  })
  it('downloads complete reusable instructions with a local return link', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'How it works' }))
    const download = screen.getByRole('link', { name: 'Download instructions' })
    expect(download).toHaveAttribute('download', 'tin-to-cellar-instructions.md')
    expect(download).toHaveAttribute('href', 'blob:label')
    const blob = vi.mocked(URL.createObjectURL).mock.calls[0][0] as Blob
    const contents = await new Promise<string>((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result))
      reader.readAsText(blob)
    })
    expect(contents).toContain('tin-to-cellar/cellarpack')
    expect(contents).toContain(`${window.location.origin}/#print`)
    expect(URL.revokeObjectURL).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Make a prompt' }))
    expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:label')
  })
  it('opens the form directly and keeps the workflow explanation in its own view', () => {
    render(<App />)
    expect(screen.getByLabelText('Tobaccos')).toBeInTheDocument()
    expect(screen.getByRole('contentinfo')).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'How it works' })).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Tobaccos'), { target: { value: 'Escudo' } })
    fireEvent.change(screen.getByLabelText('Special requests'), { target: { value: 'Cream background' } })
    fireEvent.click(screen.getByRole('button', { name: 'How it works' }))
    expect(screen.getByRole('heading', { name: 'How it works' })).toBeInTheDocument()
    expect(screen.getByText(/account you already have/)).toBeInTheDocument()
    expect(screen.getByText(/reloading or closing the page clears/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'How it works' })).toHaveAttribute('aria-current', 'page')
    fireEvent.click(screen.getByRole('button', { name: 'Make a prompt' }))
    expect(screen.getByRole('button', { name: 'Remove Escudo' })).toBeInTheDocument()
    expect(screen.getByLabelText('Special requests')).toHaveValue('Cream background')
  })
  it('preserves paper position, alignment, and preview page when switching screens', async () => {
    importer.mockResolvedValue(ready())
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '10' } })
    fireEvent.change(screen.getByLabelText('Start at slot'), { target: { value: '2' } })
    fireEvent.change(screen.getByLabelText('Horizontal adjustment'), { target: { value: '.05' } })
    fireEvent.change(screen.getByLabelText('Vertical adjustment'), { target: { value: '-.03' } })
    fireEvent.click(screen.getByRole('button', { name: 'Next sheet' }))
    fireEvent.click(screen.getByRole('button', { name: /Make a prompt/i }))
    fireEvent.click(screen.getByRole('button', { name: 'How it works' }))
    fireEvent.click(screen.getByRole('button', { name: 'Tin to Cellar home' }))
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    expect(screen.getByLabelText('Start at slot')).toHaveValue('2')
    expect(screen.getByLabelText('Horizontal adjustment')).toHaveValue(.05)
    expect(screen.getByLabelText('Vertical adjustment')).toHaveValue(-.03)
    expect(screen.getByText('Sheet 2 of 2')).toBeInTheDocument()
    expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(10)
  })
  it('offers repair for a partial archive even when every label can print', async () => {
    importer.mockResolvedValue({ ...ready(), status: 'partial', issues: [{ severity: 'error', code: 'INVALID_PROFILE', message: 'The extra sheet profile is invalid.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    expect(await screen.findByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.getByRole('button', { name: 'Copy repair request' })).toBeInTheDocument()
  })
  it('keeps ordinary warnings informational instead of requesting repair', async () => {
    importer.mockResolvedValue({ ...ready(), issues: [{ severity: 'warning', code: 'LIMITED_RESEARCH', message: 'Research was limited.' }, { severity: 'warning', code: 'MISSING_PREVIEW', message: 'Optional preview is missing.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    expect(await screen.findByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.queryByRole('button', { name: 'Copy repair request' })).not.toBeInTheDocument()
    expect(screen.queryByText('Optional preview is missing.')).not.toBeInTheDocument()
    expect(screen.getByText('Research was limited.')).toBeInTheDocument()
  })
  it('imports straight into quantity and print controls', async () => {
    importer.mockResolvedValue(ready())
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    expect(await screen.findByLabelText('Quantity for Blend A')).toHaveValue(1)
    expect(screen.getByRole('button', { name: 'Print 1 label' })).toBeInTheDocument()
    expect(screen.queryByText('Compose the sheet')).not.toBeInTheDocument()
  })
  it('preserves existing labels and quantities when a replacement ZIP is rejected', async () => {
    importer.mockResolvedValueOnce(ready()).mockResolvedValueOnce({ status: 'rejected', labels: [], quarantinedLabels: [], issues: [{ code: 'INVALID_MANIFEST', message: 'Manifest is missing artworkAssetId.' }] })
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    fireEvent.change(await screen.findByLabelText('Quantity for Blend A'), { target: { value: '3' } })
    upload()
    await screen.findByRole('button', { name: 'Copy repair request' })
    expect(screen.getByLabelText('Quantity for Blend A')).toHaveValue(3)
    expect(URL.revokeObjectURL).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Copy repair request' }))
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalled())
    expect(vi.mocked(navigator.clipboard.writeText).mock.calls[0][0]).toContain('artworkAssetId')
    expect(await screen.findByText(/Paste this into the same AI chat/)).toBeInTheDocument()
  })
  it('keeps incompatible artwork off the printed sheet and provides repair instructions', async () => {
    importer.mockResolvedValue(ready([imported('Round'), imported('Square', 'square')]))
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Print labels/i }))
    upload()
    expect(await screen.findByLabelText('Quantity for Round')).toHaveValue(1)
    expect(screen.queryByLabelText('Quantity for Square')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Copy repair request' })).toBeInTheDocument()
    expect(screen.getAllByText(/does not match this sheet/).length).toBeGreaterThan(0)
  })
})

it('extracts feedback from a pack and clears it when a later import fails', async () => {
  window.history.replaceState({}, '', '/#print')
  const feedback = {
    format: 'tin-to-cellar/feedback', schemaVersion: '1.0.0', promptVersion: '2026-09-06.1',
    request: { labelCount: 1, shape: 'circle' }, outcome: 'complete', steps: [], issues: [],
  }
  importer.mockResolvedValueOnce({ ...ready(), manifest: { title: 'Test pack', extensions: { 'tin-to-cellar:feedback': feedback } } })
  render(<App />)
  upload()
  expect(await screen.findByText(/The AI reported: complete/)).toBeInTheDocument()
  importer.mockRejectedValueOnce(new Error('Invalid ZIP'))
  upload()
  await waitFor(() => expect(screen.queryByText(/The AI reported: complete/)).not.toBeInTheDocument())
  expect(screen.getByText(/No readable feedback report/)).toBeInTheDocument()
})
